# generated by datamodel-codegen:
#   filename:  workdir/database_vultr_upbound_io_v1beta1_database.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from ....k8s.apimachinery.pkg.apis.meta import v1


class AccessCertSecretRef(BaseModel):
    key: str
    """
    The key to select.
    """
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class AccessKeySecretRef(BaseModel):
    key: str
    """
    The key to select.
    """
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class FerretdbCredentialsSecretRef(BaseModel):
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class PasswordSecretRef(BaseModel):
    key: str
    """
    The key to select.
    """
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class ReadReplica(BaseModel):
    backupHour: str | None = None
    """
    The preferred hour of the day (UTC) for daily backups to take place (unavailable for Kafka engine types).
    """
    backupMinute: str | None = None
    """
    The preferred minute of the backup hour for daily backups to take place (unavailable for Kafka engine types).
    """
    evictionPolicy: str | None = None
    """
    The configuration value for the data eviction policy on the managed database (Valkey engine types only - noeviction, allkeys-lru, volatile-lru, allkeys-random, volatile-random, volatile-ttl, volatile-lfu, allkeys-lfu).
    """
    ferretdbCredentialsSecretRef: FerretdbCredentialsSecretRef | None = None
    """
    A SecretReference is a reference to a secret in an arbitrary namespace.
    """
    label: str | None = None
    """
    A label for the managed database.
    """
    mysqlLongQueryTime: int | None = None
    """
    The configuration value for the long query time (in seconds) on the managed database (MySQL engine types only).
    """
    mysqlRequirePrimaryKey: bool | None = None
    """
    The configuration value for whether primary keys are required on the managed database (MySQL engine types only).
    """
    mysqlSlowQueryLog: bool | None = None
    """
    The configuration value for slow query logging on the managed database (MySQL engine types only).
    """
    mysqlSqlModes: list[str] | None = None
    """
    A list of SQL modes to configure for the managed database (MySQL engine types only - ALLOW_INVALID_DATES, ANSI, ANSI_QUOTES, ERROR_FOR_DIVISION_BY_ZERO, HIGH_NOT_PRECEDENCE, IGNORE_SPACE, NO_AUTO_VALUE_ON_ZERO, NO_DIR_IN_CREATE, NO_ENGINE_SUBSTITUTION, NO_UNSIGNED_SUBTRACTION, NO_ZERO_DATE, NO_ZERO_IN_DATE, ONLY_FULL_GROUP_BY, PIPES_AS_CONCAT, REAL_AS_FLOAT, STRICT_ALL_TABLES, STRICT_TRANS_TABLES, TIME_TRUNCATE_FRACTIONAL, TRADITIONAL).
    """
    planDisk: int | None = None
    """
    The description of the disk(s) on the managed database.
    """
    publicHost: str | None = None
    """
    The public hostname assigned to the managed database (VPC-attached only).
    """
    region: str | None = None
    """
    The ID of the region that the managed database is to be created in. See List Regions
    """
    tag: str | None = None
    """
    The tag to assign to the managed database.
    """
    trustedIps: list[str] | None = None
    """
    A list of allowed IP addresses for the managed database.
    """


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class VpcIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class VpcIdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ForProvider(BaseModel):
    accessCertSecretRef: AccessCertSecretRef | None = None
    """
    The certificate to authenticate the default user (Kafka engine types only).
    """
    accessKeySecretRef: AccessKeySecretRef | None = None
    """
    The private key to authenticate the default user (Kafka engine types only).
    """
    backupHour: str | None = None
    """
    The preferred hour of the day (UTC) for daily backups to take place (unavailable for Kafka engine types).
    """
    backupMinute: str | None = None
    """
    The preferred minute of the backup hour for daily backups to take place (unavailable for Kafka engine types).
    """
    clusterTimeZone: str | None = None
    """
    The configured time zone for the Managed Database in TZ database format (e.g. UTC, America/New_York, Europe/London).
    """
    databaseEngine: str | None = None
    """
    The database engine of the new managed database.
    """
    databaseEngineVersion: str | None = None
    """
    The database engine version of the new managed database.
    """
    enableKafkaConnect: bool | None = None
    """
    The configuration value for Kafka Connect support (Kafka engine types only).
    """
    enableKafkaRest: bool | None = None
    """
    The configuration value for Kafka REST support (Kafka engine types only).
    """
    enableSchemaRegistry: bool | None = None
    """
    The configuration value for Schema Registry support (Kafka engine types only).
    """
    evictionPolicy: str | None = None
    """
    The configuration value for the data eviction policy on the managed database (Valkey engine types only - noeviction, allkeys-lru, volatile-lru, allkeys-random, volatile-random, volatile-ttl, volatile-lfu, allkeys-lfu).
    """
    ferretdbCredentialsSecretRef: FerretdbCredentialsSecretRef | None = None
    """
    A SecretReference is a reference to a secret in an arbitrary namespace.
    """
    kafkaRestUri: str | None = None
    """
    The URI to access the RESTful interface of your Kafka cluster if Kafka REST is enabled (Kafka engine types only).
    """
    label: str | None = None
    """
    A label for the managed database.
    """
    maintenanceDow: str | None = None
    """
    The preferred maintenance day of week for the managed database.
    """
    maintenanceTime: str | None = None
    """
    The preferred maintenance time for the managed database.
    """
    mysqlLongQueryTime: int | None = None
    """
    The configuration value for the long query time (in seconds) on the managed database (MySQL engine types only).
    """
    mysqlRequirePrimaryKey: bool | None = None
    """
    The configuration value for whether primary keys are required on the managed database (MySQL engine types only).
    """
    mysqlSlowQueryLog: bool | None = None
    """
    The configuration value for slow query logging on the managed database (MySQL engine types only).
    """
    mysqlSqlModes: list[str] | None = None
    """
    A list of SQL modes to configure for the managed database (MySQL engine types only - ALLOW_INVALID_DATES, ANSI, ANSI_QUOTES, ERROR_FOR_DIVISION_BY_ZERO, HIGH_NOT_PRECEDENCE, IGNORE_SPACE, NO_AUTO_VALUE_ON_ZERO, NO_DIR_IN_CREATE, NO_ENGINE_SUBSTITUTION, NO_UNSIGNED_SUBTRACTION, NO_ZERO_DATE, NO_ZERO_IN_DATE, ONLY_FULL_GROUP_BY, PIPES_AS_CONCAT, REAL_AS_FLOAT, STRICT_ALL_TABLES, STRICT_TRANS_TABLES, TIME_TRUNCATE_FRACTIONAL, TRADITIONAL).
    """
    passwordSecretRef: PasswordSecretRef | None = None
    """
    The password for the managed database's primary admin user.
    """
    plan: str | None = None
    """
    The ID of the plan that you want the managed database to subscribe to. See List Managed Database Plans
    """
    planBrokers: int | None = None
    """
    The number of brokers available on the managed database (Kafka engine types only).
    """
    planDisk: int | None = None
    """
    The description of the disk(s) on the managed database.
    """
    planReplicas: int | None = None
    """
    The number of standby nodes available on the managed database (excluded for Kafka engine types).
    """
    publicHost: str | None = None
    """
    The public hostname assigned to the managed database (VPC-attached only).
    """
    readReplicas: list[ReadReplica] | None = None
    """
    A list of read replicas attached to the managed database.
    """
    region: str | None = None
    """
    The ID of the region that the managed database is to be created in. See List Regions
    """
    saslPort: str | None = None
    """
    The SASL connection port for the managed database (Kafka engine types only).
    """
    schemaRegistryUri: str | None = None
    """
    The URI to access the Schema Registry service of your Kafka cluster if Schema Registry is enabled (Kafka engine types only).
    """
    tag: str | None = None
    """
    The tag to assign to the managed database.
    """
    trustedIps: list[str] | None = None
    """
    A list of allowed IP addresses for the managed database.
    """
    vpcId: str | None = None
    """
    The ID of the VPC Network to attach to the Managed Database.
    """
    vpcIdRef: VpcIdRef | None = None
    """
    Reference to a VPC in network to populate vpcId.
    """
    vpcIdSelector: VpcIdSelector | None = None
    """
    Selector for a VPC in network to populate vpcId.
    """


class ReadReplicaModel(BaseModel):
    backupHour: str | None = None
    """
    The preferred hour of the day (UTC) for daily backups to take place (unavailable for Kafka engine types).
    """
    backupMinute: str | None = None
    """
    The preferred minute of the backup hour for daily backups to take place (unavailable for Kafka engine types).
    """
    evictionPolicy: str | None = None
    """
    The configuration value for the data eviction policy on the managed database (Valkey engine types only - noeviction, allkeys-lru, volatile-lru, allkeys-random, volatile-random, volatile-ttl, volatile-lfu, allkeys-lfu).
    """
    ferretdbCredentialsSecretRef: dict[str, str] | None = None
    label: str | None = None
    """
    A label for the managed database.
    """
    mysqlLongQueryTime: int | None = None
    """
    The configuration value for the long query time (in seconds) on the managed database (MySQL engine types only).
    """
    mysqlRequirePrimaryKey: bool | None = None
    """
    The configuration value for whether primary keys are required on the managed database (MySQL engine types only).
    """
    mysqlSlowQueryLog: bool | None = None
    """
    The configuration value for slow query logging on the managed database (MySQL engine types only).
    """
    mysqlSqlModes: list[str] | None = None
    """
    A list of SQL modes to configure for the managed database (MySQL engine types only - ALLOW_INVALID_DATES, ANSI, ANSI_QUOTES, ERROR_FOR_DIVISION_BY_ZERO, HIGH_NOT_PRECEDENCE, IGNORE_SPACE, NO_AUTO_VALUE_ON_ZERO, NO_DIR_IN_CREATE, NO_ENGINE_SUBSTITUTION, NO_UNSIGNED_SUBTRACTION, NO_ZERO_DATE, NO_ZERO_IN_DATE, ONLY_FULL_GROUP_BY, PIPES_AS_CONCAT, REAL_AS_FLOAT, STRICT_ALL_TABLES, STRICT_TRANS_TABLES, TIME_TRUNCATE_FRACTIONAL, TRADITIONAL).
    """
    planDisk: int | None = None
    """
    The description of the disk(s) on the managed database.
    """
    publicHost: str | None = None
    """
    The public hostname assigned to the managed database (VPC-attached only).
    """
    region: str | None = None
    """
    The ID of the region that the managed database is to be created in. See List Regions
    """
    tag: str | None = None
    """
    The tag to assign to the managed database.
    """
    trustedIps: list[str] | None = None
    """
    A list of allowed IP addresses for the managed database.
    """


class InitProvider(BaseModel):
    accessCertSecretRef: AccessCertSecretRef | None = None
    """
    The certificate to authenticate the default user (Kafka engine types only).
    """
    accessKeySecretRef: AccessKeySecretRef | None = None
    """
    The private key to authenticate the default user (Kafka engine types only).
    """
    backupHour: str | None = None
    """
    The preferred hour of the day (UTC) for daily backups to take place (unavailable for Kafka engine types).
    """
    backupMinute: str | None = None
    """
    The preferred minute of the backup hour for daily backups to take place (unavailable for Kafka engine types).
    """
    clusterTimeZone: str | None = None
    """
    The configured time zone for the Managed Database in TZ database format (e.g. UTC, America/New_York, Europe/London).
    """
    databaseEngine: str | None = None
    """
    The database engine of the new managed database.
    """
    databaseEngineVersion: str | None = None
    """
    The database engine version of the new managed database.
    """
    enableKafkaConnect: bool | None = None
    """
    The configuration value for Kafka Connect support (Kafka engine types only).
    """
    enableKafkaRest: bool | None = None
    """
    The configuration value for Kafka REST support (Kafka engine types only).
    """
    enableSchemaRegistry: bool | None = None
    """
    The configuration value for Schema Registry support (Kafka engine types only).
    """
    evictionPolicy: str | None = None
    """
    The configuration value for the data eviction policy on the managed database (Valkey engine types only - noeviction, allkeys-lru, volatile-lru, allkeys-random, volatile-random, volatile-ttl, volatile-lfu, allkeys-lfu).
    """
    ferretdbCredentialsSecretRef: dict[str, str] | None = None
    kafkaRestUri: str | None = None
    """
    The URI to access the RESTful interface of your Kafka cluster if Kafka REST is enabled (Kafka engine types only).
    """
    label: str | None = None
    """
    A label for the managed database.
    """
    maintenanceDow: str | None = None
    """
    The preferred maintenance day of week for the managed database.
    """
    maintenanceTime: str | None = None
    """
    The preferred maintenance time for the managed database.
    """
    mysqlLongQueryTime: int | None = None
    """
    The configuration value for the long query time (in seconds) on the managed database (MySQL engine types only).
    """
    mysqlRequirePrimaryKey: bool | None = None
    """
    The configuration value for whether primary keys are required on the managed database (MySQL engine types only).
    """
    mysqlSlowQueryLog: bool | None = None
    """
    The configuration value for slow query logging on the managed database (MySQL engine types only).
    """
    mysqlSqlModes: list[str] | None = None
    """
    A list of SQL modes to configure for the managed database (MySQL engine types only - ALLOW_INVALID_DATES, ANSI, ANSI_QUOTES, ERROR_FOR_DIVISION_BY_ZERO, HIGH_NOT_PRECEDENCE, IGNORE_SPACE, NO_AUTO_VALUE_ON_ZERO, NO_DIR_IN_CREATE, NO_ENGINE_SUBSTITUTION, NO_UNSIGNED_SUBTRACTION, NO_ZERO_DATE, NO_ZERO_IN_DATE, ONLY_FULL_GROUP_BY, PIPES_AS_CONCAT, REAL_AS_FLOAT, STRICT_ALL_TABLES, STRICT_TRANS_TABLES, TIME_TRUNCATE_FRACTIONAL, TRADITIONAL).
    """
    passwordSecretRef: PasswordSecretRef | None = None
    """
    The password for the managed database's primary admin user.
    """
    plan: str | None = None
    """
    The ID of the plan that you want the managed database to subscribe to. See List Managed Database Plans
    """
    planBrokers: int | None = None
    """
    The number of brokers available on the managed database (Kafka engine types only).
    """
    planDisk: int | None = None
    """
    The description of the disk(s) on the managed database.
    """
    planReplicas: int | None = None
    """
    The number of standby nodes available on the managed database (excluded for Kafka engine types).
    """
    publicHost: str | None = None
    """
    The public hostname assigned to the managed database (VPC-attached only).
    """
    readReplicas: list[ReadReplicaModel] | None = None
    """
    A list of read replicas attached to the managed database.
    """
    region: str | None = None
    """
    The ID of the region that the managed database is to be created in. See List Regions
    """
    saslPort: str | None = None
    """
    The SASL connection port for the managed database (Kafka engine types only).
    """
    schemaRegistryUri: str | None = None
    """
    The URI to access the Schema Registry service of your Kafka cluster if Schema Registry is enabled (Kafka engine types only).
    """
    tag: str | None = None
    """
    The tag to assign to the managed database.
    """
    trustedIps: list[str] | None = None
    """
    A list of allowed IP addresses for the managed database.
    """
    vpcId: str | None = None
    """
    The ID of the VPC Network to attach to the Managed Database.
    """
    vpcIdRef: VpcIdRef | None = None
    """
    Reference to a VPC in network to populate vpcId.
    """
    vpcIdSelector: VpcIdSelector | None = None
    """
    Selector for a VPC in network to populate vpcId.
    """


class ProviderConfigRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class Spec(BaseModel):
    deletionPolicy: Literal['Orphan', 'Delete'] | None = 'Delete'
    """
    DeletionPolicy specifies what will happen to the underlying external
    when this managed resource is deleted - either "Delete" or "Orphan" the
    external resource.
    This field is planned to be deprecated in favor of the ManagementPolicies
    field in a future release. Currently, both could be set independently and
    non-default values would be honored if the feature flag is enabled.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    """
    forProvider: ForProvider
    initProvider: InitProvider | None = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    This field is planned to replace the DeletionPolicy field in a future
    release. Currently, both could be set independently and non-default
    values would be honored if the feature flag is enabled. If both are
    custom, the DeletionPolicy field will be ignored.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class ReadReplicaModel1(BaseModel):
    backupHour: str | None = None
    """
    The preferred hour of the day (UTC) for daily backups to take place (unavailable for Kafka engine types).
    """
    backupMinute: str | None = None
    """
    The preferred minute of the backup hour for daily backups to take place (unavailable for Kafka engine types).
    """
    caCertificate: str | None = None
    """
    The CA certificate for Managed Databases on this account.
    """
    clusterTimeZone: str | None = None
    """
    The configured time zone for the Managed Database in TZ database format (e.g. UTC, America/New_York, Europe/London).
    """
    databaseEngine: str | None = None
    """
    The database engine of the new managed database.
    """
    databaseEngineVersion: str | None = None
    """
    The database engine version of the new managed database.
    """
    dateCreated: str | None = None
    """
    The date the managed database was added to your Vultr account.
    """
    dbname: str | None = None
    """
    The managed database's default logical database.
    """
    evictionPolicy: str | None = None
    """
    The configuration value for the data eviction policy on the managed database (Valkey engine types only - noeviction, allkeys-lru, volatile-lru, allkeys-random, volatile-random, volatile-ttl, volatile-lfu, allkeys-lfu).
    """
    host: str | None = None
    """
    The hostname assigned to the managed database.
    """
    id: str | None = None
    """
    The ID of the managed database.
    """
    label: str | None = None
    """
    A label for the managed database.
    """
    latestBackup: str | None = None
    """
    The date of the latest backup available on the managed database.
    """
    maintenanceDow: str | None = None
    """
    The preferred maintenance day of week for the managed database.
    """
    maintenanceTime: str | None = None
    """
    The preferred maintenance time for the managed database.
    """
    mysqlLongQueryTime: int | None = None
    """
    The configuration value for the long query time (in seconds) on the managed database (MySQL engine types only).
    """
    mysqlRequirePrimaryKey: bool | None = None
    """
    The configuration value for whether primary keys are required on the managed database (MySQL engine types only).
    """
    mysqlSlowQueryLog: bool | None = None
    """
    The configuration value for slow query logging on the managed database (MySQL engine types only).
    """
    mysqlSqlModes: list[str] | None = None
    """
    A list of SQL modes to configure for the managed database (MySQL engine types only - ALLOW_INVALID_DATES, ANSI, ANSI_QUOTES, ERROR_FOR_DIVISION_BY_ZERO, HIGH_NOT_PRECEDENCE, IGNORE_SPACE, NO_AUTO_VALUE_ON_ZERO, NO_DIR_IN_CREATE, NO_ENGINE_SUBSTITUTION, NO_UNSIGNED_SUBTRACTION, NO_ZERO_DATE, NO_ZERO_IN_DATE, ONLY_FULL_GROUP_BY, PIPES_AS_CONCAT, REAL_AS_FLOAT, STRICT_ALL_TABLES, STRICT_TRANS_TABLES, TIME_TRUNCATE_FRACTIONAL, TRADITIONAL).
    """
    plan: str | None = None
    """
    The ID of the plan that you want the managed database to subscribe to. See List Managed Database Plans
    """
    planDisk: int | None = None
    """
    The description of the disk(s) on the managed database.
    """
    planRam: int | None = None
    """
    The amount of memory available on the managed database in MB.
    """
    planReplicas: int | None = None
    """
    The number of standby nodes available on the managed database (excluded for Kafka engine types).
    """
    planVcpus: int | None = None
    """
    The number of virtual CPUs available on the managed database.
    """
    port: str | None = None
    """
    The connection port for the managed database.
    """
    publicHost: str | None = None
    """
    The public hostname assigned to the managed database (VPC-attached only).
    """
    region: str | None = None
    """
    The ID of the region that the managed database is to be created in. See List Regions
    """
    status: str | None = None
    """
    The current status of the managed database (poweroff, rebuilding, rebalancing, configuring, running).
    """
    tag: str | None = None
    """
    The tag to assign to the managed database.
    """
    trustedIps: list[str] | None = None
    """
    A list of allowed IP addresses for the managed database.
    """
    user: str | None = None
    """
    The primary admin user for the managed database.
    """
    vpcId: str | None = None
    """
    The ID of the VPC Network to attach to the Managed Database.
    """


class AtProvider(BaseModel):
    backupHour: str | None = None
    """
    The preferred hour of the day (UTC) for daily backups to take place (unavailable for Kafka engine types).
    """
    backupMinute: str | None = None
    """
    The preferred minute of the backup hour for daily backups to take place (unavailable for Kafka engine types).
    """
    caCertificate: str | None = None
    """
    The CA certificate for Managed Databases on this account.
    """
    clusterTimeZone: str | None = None
    """
    The configured time zone for the Managed Database in TZ database format (e.g. UTC, America/New_York, Europe/London).
    """
    databaseEngine: str | None = None
    """
    The database engine of the new managed database.
    """
    databaseEngineVersion: str | None = None
    """
    The database engine version of the new managed database.
    """
    dateCreated: str | None = None
    """
    The date the managed database was added to your Vultr account.
    """
    dbname: str | None = None
    """
    The managed database's default logical database.
    """
    enableKafkaConnect: bool | None = None
    """
    The configuration value for Kafka Connect support (Kafka engine types only).
    """
    enableKafkaRest: bool | None = None
    """
    The configuration value for Kafka REST support (Kafka engine types only).
    """
    enableSchemaRegistry: bool | None = None
    """
    The configuration value for Schema Registry support (Kafka engine types only).
    """
    evictionPolicy: str | None = None
    """
    The configuration value for the data eviction policy on the managed database (Valkey engine types only - noeviction, allkeys-lru, volatile-lru, allkeys-random, volatile-random, volatile-ttl, volatile-lfu, allkeys-lfu).
    """
    host: str | None = None
    """
    The hostname assigned to the managed database.
    """
    id: str | None = None
    """
    The ID of the managed database.
    """
    kafkaRestUri: str | None = None
    """
    The URI to access the RESTful interface of your Kafka cluster if Kafka REST is enabled (Kafka engine types only).
    """
    label: str | None = None
    """
    A label for the managed database.
    """
    latestBackup: str | None = None
    """
    The date of the latest backup available on the managed database.
    """
    maintenanceDow: str | None = None
    """
    The preferred maintenance day of week for the managed database.
    """
    maintenanceTime: str | None = None
    """
    The preferred maintenance time for the managed database.
    """
    mysqlLongQueryTime: int | None = None
    """
    The configuration value for the long query time (in seconds) on the managed database (MySQL engine types only).
    """
    mysqlRequirePrimaryKey: bool | None = None
    """
    The configuration value for whether primary keys are required on the managed database (MySQL engine types only).
    """
    mysqlSlowQueryLog: bool | None = None
    """
    The configuration value for slow query logging on the managed database (MySQL engine types only).
    """
    mysqlSqlModes: list[str] | None = None
    """
    A list of SQL modes to configure for the managed database (MySQL engine types only - ALLOW_INVALID_DATES, ANSI, ANSI_QUOTES, ERROR_FOR_DIVISION_BY_ZERO, HIGH_NOT_PRECEDENCE, IGNORE_SPACE, NO_AUTO_VALUE_ON_ZERO, NO_DIR_IN_CREATE, NO_ENGINE_SUBSTITUTION, NO_UNSIGNED_SUBTRACTION, NO_ZERO_DATE, NO_ZERO_IN_DATE, ONLY_FULL_GROUP_BY, PIPES_AS_CONCAT, REAL_AS_FLOAT, STRICT_ALL_TABLES, STRICT_TRANS_TABLES, TIME_TRUNCATE_FRACTIONAL, TRADITIONAL).
    """
    pendingCharges: float | None = None
    """
    Charges due for this managed database subscription at the end of the billing period.
    """
    plan: str | None = None
    """
    The ID of the plan that you want the managed database to subscribe to. See List Managed Database Plans
    """
    planBrokers: int | None = None
    """
    The number of brokers available on the managed database (Kafka engine types only).
    """
    planDisk: int | None = None
    """
    The description of the disk(s) on the managed database.
    """
    planRam: int | None = None
    """
    The amount of memory available on the managed database in MB.
    """
    planReplicas: int | None = None
    """
    The number of standby nodes available on the managed database (excluded for Kafka engine types).
    """
    planVcpus: int | None = None
    """
    The number of virtual CPUs available on the managed database.
    """
    port: str | None = None
    """
    The connection port for the managed database.
    """
    publicHost: str | None = None
    """
    The public hostname assigned to the managed database (VPC-attached only).
    """
    readReplicas: list[ReadReplicaModel1] | None = None
    """
    A list of read replicas attached to the managed database.
    """
    region: str | None = None
    """
    The ID of the region that the managed database is to be created in. See List Regions
    """
    saslPort: str | None = None
    """
    The SASL connection port for the managed database (Kafka engine types only).
    """
    schemaRegistryUri: str | None = None
    """
    The URI to access the Schema Registry service of your Kafka cluster if Schema Registry is enabled (Kafka engine types only).
    """
    status: str | None = None
    """
    The current status of the managed database (poweroff, rebuilding, rebalancing, configuring, running).
    """
    tag: str | None = None
    """
    The tag to assign to the managed database.
    """
    trustedIps: list[str] | None = None
    """
    A list of allowed IP addresses for the managed database.
    """
    user: str | None = None
    """
    The primary admin user for the managed database.
    """
    vpcId: str | None = None
    """
    The ID of the VPC Network to attach to the Managed Database.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    lastHandledReconcileAt: str | None = None
    """
    LastHandledReconcileAt holds the value of the most recent
    reconcile-requested-at annotation token that the controller has
    processed. Users can compare this to the annotation to determine
    whether a reconcile request has been handled.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class Database(BaseModel):
    apiVersion: Literal['database.vultr.upbound.io/v1beta1'] | None = (
        'database.vultr.upbound.io/v1beta1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['Database'] | None = 'Database'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    DatabaseSpec defines the desired state of Database
    """
    status: Status | None = None
    """
    DatabaseStatus defines the observed state of Database.
    """


class DatabaseList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[Database]
    """
    List of databases. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """