# generated by datamodel-codegen:
#   filename:  workdir/vke_vultr_upbound_io_v1beta1_kubernetesnodepool.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from .....k8s.apimachinery.pkg.apis.meta import v1


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class ClusterIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class ClusterIdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class Label(BaseModel):
    key: str | None = None
    """
    The key definining the label for kubernetes.
    """
    value: str | None = None
    """
    The value of the label for kubernetes.
    """


class Taint(BaseModel):
    effect: str | None = None
    """
    The effect of the taint for kubernetes.  Must be one of NoSchedule, PreferNoSchedule or NoExecute.
    """
    key: str | None = None
    """
    The key definining the label for kubernetes.
    """
    value: str | None = None
    """
    The value of the label for kubernetes.
    """


class ForProvider(BaseModel):
    autoScaler: bool | None = None
    """
    Enable the auto scaler for the default node pool.
    """
    clusterId: str | None = None
    """
    The VKE cluster ID you want to attach this nodepool to.
    """
    clusterIdRef: ClusterIdRef | None = None
    """
    Reference to a Kubernetes in vke to populate clusterId.
    """
    clusterIdSelector: ClusterIdSelector | None = None
    """
    Selector for a Kubernetes in vke to populate clusterId.
    """
    label: str | None = None
    """
    The label to be used as a prefix for nodes in this node pool.
    """
    labels: list[Label] | None = None
    maxNodes: int | None = None
    """
    The maximum number of nodes to use with the auto scaler.
    """
    minNodes: int | None = None
    """
    The minimum number of nodes to use with the auto scaler.
    """
    nodeQuantity: int | None = None
    """
    The number of nodes in this node pool.
    """
    plan: str | None = None
    """
    The plan to be used in this node pool. See plans list Note the minimum plan requirements must have at least 1 core and 2 gbs of memory.
    """
    tag: str | None = None
    """
    A tag that is assigned to this node pool.
    """
    taints: list[Taint] | None = None
    userData: str | None = None
    """
    A base64 encoded string containing the user data to apply to nodes in the node pool.
    """


class InitProvider(BaseModel):
    autoScaler: bool | None = None
    """
    Enable the auto scaler for the default node pool.
    """
    clusterId: str | None = None
    """
    The VKE cluster ID you want to attach this nodepool to.
    """
    clusterIdRef: ClusterIdRef | None = None
    """
    Reference to a Kubernetes in vke to populate clusterId.
    """
    clusterIdSelector: ClusterIdSelector | None = None
    """
    Selector for a Kubernetes in vke to populate clusterId.
    """
    label: str | None = None
    """
    The label to be used as a prefix for nodes in this node pool.
    """
    labels: list[Label] | None = None
    maxNodes: int | None = None
    """
    The maximum number of nodes to use with the auto scaler.
    """
    minNodes: int | None = None
    """
    The minimum number of nodes to use with the auto scaler.
    """
    nodeQuantity: int | None = None
    """
    The number of nodes in this node pool.
    """
    plan: str | None = None
    """
    The plan to be used in this node pool. See plans list Note the minimum plan requirements must have at least 1 core and 2 gbs of memory.
    """
    tag: str | None = None
    """
    A tag that is assigned to this node pool.
    """
    taints: list[Taint] | None = None
    userData: str | None = None
    """
    A base64 encoded string containing the user data to apply to nodes in the node pool.
    """


class ProviderConfigRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class Spec(BaseModel):
    deletionPolicy: Literal['Orphan', 'Delete'] | None = 'Delete'
    """
    DeletionPolicy specifies what will happen to the underlying external
    when this managed resource is deleted - either "Delete" or "Orphan" the
    external resource.
    This field is planned to be deprecated in favor of the ManagementPolicies
    field in a future release. Currently, both could be set independently and
    non-default values would be honored if the feature flag is enabled.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    """
    forProvider: ForProvider
    initProvider: InitProvider | None = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    This field is planned to replace the DeletionPolicy field in a future
    release. Currently, both could be set independently and non-default
    values would be honored if the feature flag is enabled. If both are
    custom, the DeletionPolicy field will be ignored.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class LabelModel(BaseModel):
    id: str | None = None
    """
    The Nodepool ID.
    """
    key: str | None = None
    """
    The key definining the label for kubernetes.
    """
    value: str | None = None
    """
    The value of the label for kubernetes.
    """


class Node(BaseModel):
    dateCreated: str | None = None
    """
    Date of node pool creation.
    """
    id: str | None = None
    """
    The Nodepool ID.
    """
    label: str | None = None
    """
    The label to be used as a prefix for nodes in this node pool.
    """
    status: str | None = None
    """
    Status of node pool.
    """


class TaintModel(BaseModel):
    effect: str | None = None
    """
    The effect of the taint for kubernetes.  Must be one of NoSchedule, PreferNoSchedule or NoExecute.
    """
    id: str | None = None
    """
    The Nodepool ID.
    """
    key: str | None = None
    """
    The key definining the label for kubernetes.
    """
    value: str | None = None
    """
    The value of the label for kubernetes.
    """


class AtProvider(BaseModel):
    autoScaler: bool | None = None
    """
    Enable the auto scaler for the default node pool.
    """
    clusterId: str | None = None
    """
    The VKE cluster ID you want to attach this nodepool to.
    """
    dateCreated: str | None = None
    """
    Date of node pool creation.
    """
    dateUpdated: str | None = None
    """
    Date of node pool updates.
    """
    id: str | None = None
    """
    The Nodepool ID.
    """
    label: str | None = None
    """
    The label to be used as a prefix for nodes in this node pool.
    """
    labels: list[LabelModel] | None = None
    maxNodes: int | None = None
    """
    The maximum number of nodes to use with the auto scaler.
    """
    minNodes: int | None = None
    """
    The minimum number of nodes to use with the auto scaler.
    """
    nodeQuantity: int | None = None
    """
    The number of nodes in this node pool.
    """
    nodes: list[Node] | None = None
    plan: str | None = None
    """
    The plan to be used in this node pool. See plans list Note the minimum plan requirements must have at least 1 core and 2 gbs of memory.
    """
    status: str | None = None
    """
    Status of node pool.
    """
    tag: str | None = None
    """
    A tag that is assigned to this node pool.
    """
    taints: list[TaintModel] | None = None
    userData: str | None = None
    """
    A base64 encoded string containing the user data to apply to nodes in the node pool.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    lastHandledReconcileAt: str | None = None
    """
    LastHandledReconcileAt holds the value of the most recent
    reconcile-requested-at annotation token that the controller has
    processed. Users can compare this to the annotation to determine
    whether a reconcile request has been handled.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class KubernetesNodePool(BaseModel):
    apiVersion: Literal['vke.vultr.upbound.io/v1beta1'] | None = (
        'vke.vultr.upbound.io/v1beta1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['KubernetesNodePool'] | None = 'KubernetesNodePool'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    KubernetesNodePoolSpec defines the desired state of KubernetesNodePool
    """
    status: Status | None = None
    """
    KubernetesNodePoolStatus defines the observed state of KubernetesNodePool.
    """


class KubernetesNodePoolList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[KubernetesNodePool]
    """
    List of kubernetesnodepools. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """