# generated by datamodel-codegen:
#   filename:  workdir/storage_vultr_m_upbound_io_v1beta1_blockstorage.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from ......k8s.apimachinery.pkg.apis.meta import v1


class ForProvider(BaseModel):
    attachedToInstance: str | None = None
    """
    VPS ID that is attached to this block storage.
    """
    blockType: str | None = None
    """
    The type of block storage volume. Values are high_perf or storage_opt.
    """
    bootable: bool | None = None
    """
    Whether or not this block device can be used as a bootable volume.
    """
    label: str | None = None
    """
    Label that is given to your block storage.
    """
    live: bool | None = None
    """
    Flag which will determine if a volume should be attached with a restart or not.
    """
    osId: int | None = None
    """
    The operating system ID for this bootable block device, if applicable.
    """
    region: str | None = None
    """
    Region in which this block storage will reside in.
    """
    sizeGb: int | None = None
    """
    The size of the given block storage.
    """
    snapshotId: str | None = None
    """
    The snapshot_id from which this block device was cloned.
    """


class InitProvider(BaseModel):
    attachedToInstance: str | None = None
    """
    VPS ID that is attached to this block storage.
    """
    blockType: str | None = None
    """
    The type of block storage volume. Values are high_perf or storage_opt.
    """
    bootable: bool | None = None
    """
    Whether or not this block device can be used as a bootable volume.
    """
    label: str | None = None
    """
    Label that is given to your block storage.
    """
    live: bool | None = None
    """
    Flag which will determine if a volume should be attached with a restart or not.
    """
    osId: int | None = None
    """
    The operating system ID for this bootable block device, if applicable.
    """
    region: str | None = None
    """
    Region in which this block storage will reside in.
    """
    sizeGb: int | None = None
    """
    The size of the given block storage.
    """
    snapshotId: str | None = None
    """
    The snapshot_id from which this block device was cloned.
    """


class ProviderConfigRef(BaseModel):
    kind: str
    """
    Kind of the referenced object.
    """
    name: str
    """
    Name of the referenced object.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """


class Spec(BaseModel):
    forProvider: ForProvider
    initProvider: InitProvider | None = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'kind': 'ClusterProviderConfig', 'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class AtProvider(BaseModel):
    attachedToInstance: str | None = None
    """
    VPS ID that is attached to this block storage.
    """
    attachedToInstanceIp: str | None = None
    """
    IP address of the VPS the block storage subscription is attached to.
    """
    attachedToInstanceLabel: str | None = None
    """
    Label of the VPS the block storage subscription is attached to.
    """
    blockType: str | None = None
    """
    The type of block storage volume. Values are high_perf or storage_opt.
    """
    bootable: bool | None = None
    """
    Whether or not this block device can be used as a bootable volume.
    """
    cost: int | None = None
    """
    The monthly cost of this block storage.
    """
    dateCreated: str | None = None
    """
    The date this block storage was created.
    """
    id: str | None = None
    """
    The ID for this block storage.
    """
    label: str | None = None
    """
    Label that is given to your block storage.
    """
    live: bool | None = None
    """
    Flag which will determine if a volume should be attached with a restart or not.
    """
    mountId: str | None = None
    """
    An ID associated with the instance, when mounted the ID can be found in /dev/disk/by-id prefixed with virtio.
    """
    osId: int | None = None
    """
    The operating system ID for this bootable block device, if applicable.
    """
    pendingCharges: float | None = None
    """
    Charges due for this block storage subscription at the end of the billing period.
    """
    region: str | None = None
    """
    Region in which this block storage will reside in.
    """
    sizeGb: int | None = None
    """
    The size of the given block storage.
    """
    snapshotId: str | None = None
    """
    The snapshot_id from which this block device was cloned.
    """
    status: str | None = None
    """
    Current status of your block storage.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    lastHandledReconcileAt: str | None = None
    """
    LastHandledReconcileAt holds the value of the most recent
    reconcile-requested-at annotation token that the controller has
    processed. Users can compare this to the annotation to determine
    whether a reconcile request has been handled.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class BlockStorage(BaseModel):
    apiVersion: Literal['storage.vultr.m.upbound.io/v1beta1'] | None = (
        'storage.vultr.m.upbound.io/v1beta1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['BlockStorage'] | None = 'BlockStorage'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    BlockStorageSpec defines the desired state of BlockStorage
    """
    status: Status | None = None
    """
    BlockStorageStatus defines the observed state of BlockStorage.
    """


class BlockStorageList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[BlockStorage]
    """
    List of blockstorages. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """