# generated by datamodel-codegen:
#   filename:  workdir/storage_vultr_upbound_io_v1beta1_virtualfilesystemstorage.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from .....k8s.apimachinery.pkg.apis.meta import v1


class ForProvider(BaseModel):
    attachedInstances: list[str] | None = None
    """
    A list of UUIDs to attach to the virtual file system storage subscription.
    """
    diskType: str | None = None
    """
    The underlying disk type to use for the virtual file system storage.  Default is nvme.
    """
    label: str | None = None
    """
    The label to give to the virtual file system storage subscription.
    """
    region: str | None = None
    """
    The region in which this virtual file system storage will reside.
    """
    sizeGb: int | None = None
    """
    The size of the given virtual file system storage subscription.
    """
    tags: list[str] | None = None
    """
    A list of tags to be used on the virtual file system storage subscription.
    """


class InitProvider(BaseModel):
    attachedInstances: list[str] | None = None
    """
    A list of UUIDs to attach to the virtual file system storage subscription.
    """
    diskType: str | None = None
    """
    The underlying disk type to use for the virtual file system storage.  Default is nvme.
    """
    label: str | None = None
    """
    The label to give to the virtual file system storage subscription.
    """
    region: str | None = None
    """
    The region in which this virtual file system storage will reside.
    """
    sizeGb: int | None = None
    """
    The size of the given virtual file system storage subscription.
    """
    tags: list[str] | None = None
    """
    A list of tags to be used on the virtual file system storage subscription.
    """


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class ProviderConfigRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class Spec(BaseModel):
    deletionPolicy: Literal['Orphan', 'Delete'] | None = 'Delete'
    """
    DeletionPolicy specifies what will happen to the underlying external
    when this managed resource is deleted - either "Delete" or "Orphan" the
    external resource.
    This field is planned to be deprecated in favor of the ManagementPolicies
    field in a future release. Currently, both could be set independently and
    non-default values would be honored if the feature flag is enabled.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    """
    forProvider: ForProvider
    initProvider: InitProvider | None = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    This field is planned to replace the DeletionPolicy field in a future
    release. Currently, both could be set independently and non-default
    values would be honored if the feature flag is enabled. If both are
    custom, the DeletionPolicy field will be ignored.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class Attachment(BaseModel):
    instanceId: str | None = None
    mount: int | None = None
    state: str | None = None


class AtProvider(BaseModel):
    attachedInstances: list[str] | None = None
    """
    A list of UUIDs to attach to the virtual file system storage subscription.
    """
    attachments: list[Attachment] | None = None
    """
    A list of attchment states for instances currently attached to the virtual file system storage.
    """
    charges: float | None = None
    """
    The current pending charges for the virtual file system storage subscription in USD.
    """
    cost: float | None = None
    """
    The cost per month of the virtual file system storage subscription in USD.
    """
    dateCreated: str | None = None
    """
    The date the virtual file system storage subscription was added to your Vultr account.
    """
    diskType: str | None = None
    """
    The underlying disk type to use for the virtual file system storage.  Default is nvme.
    """
    id: str | None = None
    label: str | None = None
    """
    The label to give to the virtual file system storage subscription.
    """
    region: str | None = None
    """
    The region in which this virtual file system storage will reside.
    """
    sizeGb: int | None = None
    """
    The size of the given virtual file system storage subscription.
    """
    status: str | None = None
    """
    The status of the virtual file system storage subscription.
    """
    tags: list[str] | None = None
    """
    A list of tags to be used on the virtual file system storage subscription.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    lastHandledReconcileAt: str | None = None
    """
    LastHandledReconcileAt holds the value of the most recent
    reconcile-requested-at annotation token that the controller has
    processed. Users can compare this to the annotation to determine
    whether a reconcile request has been handled.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class VirtualFileSystemStorage(BaseModel):
    apiVersion: Literal['storage.vultr.upbound.io/v1beta1'] | None = (
        'storage.vultr.upbound.io/v1beta1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['VirtualFileSystemStorage'] | None = 'VirtualFileSystemStorage'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    VirtualFileSystemStorageSpec defines the desired state of VirtualFileSystemStorage
    """
    status: Status | None = None
    """
    VirtualFileSystemStorageStatus defines the observed state of VirtualFileSystemStorage.
    """


class VirtualFileSystemStorageList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[VirtualFileSystemStorage]
    """
    List of virtualfilesystemstorages. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """