# generated by datamodel-codegen:
#   filename:  workdir/compute_vultr_m_upbound_io_v1beta1_instance.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from ......k8s.apimachinery.pkg.apis.meta import v1


class BackupsSchedule(BaseModel):
    dom: int | None = None
    """
    Day of month to run. Use values between 1 and 28.
    """
    dow: int | None = None
    """
    Day of week to run. 1 = Sunday, 2 = Monday, 3 = Tuesday, 4 = Wednesday, 5 = Thursday, 6 = Friday, 7 = Saturday
    """
    hour: int | None = None
    """
    Hour of day to run in UTC.
    """
    type: str | None = None
    """
    Type of backup schedule Possible values are daily, weekly, monthly, daily_alt_even, or daily_alt_odd.
    """


class BlockDevice(BaseModel):
    blockId: str | None = None
    """
    The ID of an existing block device or local if the VX1 plan has local storage and you wish to utilize it for this instance.
    """
    bootable: bool | None = None
    """
    Whether the associated block device is bootable.
    """
    diskSize: int | None = None
    """
    The disk size for the block device if it is being created.
    """
    label: str | None = None
    """
    The label for the block device if it is being created.
    """


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class FirewallGroupIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class FirewallGroupIdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class IsoIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class IsoIdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ReservedIpIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class ReservedIpIdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ScriptIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class ScriptIdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class SnapshotIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class SnapshotIdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class SshKeyIdsRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class SshKeyIdsSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class VpcIdsRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class VpcIdsSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ForProvider(BaseModel):
    activationEmail: bool | None = None
    """
    Whether an activation email will be sent when the server is ready.
    """
    appId: int | None = None
    """
    The ID of the Vultr application to be installed on the server. See List Applications
    """
    appVariables: dict[str, str] | None = None
    """
    A map of user-supplied variable keys and values for Vultr Marketplace apps. See List Marketplace App Variables
    """
    backups: str | None = None
    """
    Whether automatic backups will be enabled for this server (these have an extra charge associated with them). Values can be enabled or disabled.
    """
    backupsSchedule: BackupsSchedule | None = None
    """
    A block that defines the way backups should be scheduled. While this is an optional field if backups are enabled this field is mandatory. The configuration of a backups_schedule is listed below.
    """
    blockDevices: list[BlockDevice] | None = None
    ddosProtection: bool | None = None
    """
    Whether DDOS protection will be enabled on the server (there is an additional charge for this).
    """
    disablePublicIpv4: bool | None = None
    """
    Whether the server has a public IPv4 address assigned (only possible with enable_ipv6 set to true)
    Don't set up a public IPv4 address when IPv6 is enabled.
    Will not do anything unless enable_ipv6 is also true.
    """
    enableIpv6: bool | None = None
    """
    Whether the server has IPv6 networking activated.
    """
    firewallGroupId: str | None = None
    """
    The ID of the firewall group to assign to the server.
    """
    firewallGroupIdRef: FirewallGroupIdRef | None = None
    """
    Reference to a FirewallGroup in network to populate firewallGroupId.
    """
    firewallGroupIdSelector: FirewallGroupIdSelector | None = None
    """
    Selector for a FirewallGroup in network to populate firewallGroupId.
    """
    hostname: str | None = None
    """
    The hostname to assign to the server.
    The hostname of the instance. Updating the
    hostname will cause a force new. This behavior is in place to prevent accidental reinstalls. Issuing an update to the
    hostname on UI or API issues a reinstall of the OS.
    """
    imageId: str | None = None
    """
    The ID of the Vultr marketplace application to be installed on the server. See List Applications Note marketplace applications are denoted by type: marketplace and you must use the image_id not the id.
    """
    ipxeChainUrl: str | None = None
    """
    The URL location of the iPXE chainloader.
    """
    isoId: str | None = None
    """
    The ID of the ISO file to be installed on the server. See List ISO
    """
    isoIdRef: IsoIdRef | None = None
    """
    Reference to a ISOPrivate in compute to populate isoId.
    """
    isoIdSelector: IsoIdSelector | None = None
    """
    Selector for a ISOPrivate in compute to populate isoId.
    """
    label: str | None = None
    """
    A label for the server.
    """
    osId: int | None = None
    """
    The ID of the operating system to be installed on the server. See List OS
    """
    plan: str | None = None
    """
    The ID of the plan that you want the instance to subscribe to. See List Plans
    """
    region: str | None = None
    """
    The ID of the region that the instance is to be created in. See List Regions
    """
    reservedIpId: str | None = None
    """
    ID of the floating IP to use as the main IP of this server.
    """
    reservedIpIdRef: ReservedIpIdRef | None = None
    """
    Reference to a ReservedIP in network to populate reservedIpId.
    """
    reservedIpIdSelector: ReservedIpIdSelector | None = None
    """
    Selector for a ReservedIP in network to populate reservedIpId.
    """
    scriptId: str | None = None
    """
    The ID of the startup script you want added to the server.
    """
    scriptIdRef: ScriptIdRef | None = None
    """
    Reference to a StartupScript in compute to populate scriptId.
    """
    scriptIdSelector: ScriptIdSelector | None = None
    """
    Selector for a StartupScript in compute to populate scriptId.
    """
    snapshotId: str | None = None
    """
    The ID of the Vultr snapshot that the server will restore for the initial installation. See List Snapshots
    """
    snapshotIdRef: SnapshotIdRef | None = None
    """
    Reference to a Snapshot in compute to populate snapshotId.
    """
    snapshotIdSelector: SnapshotIdSelector | None = None
    """
    Selector for a Snapshot in compute to populate snapshotId.
    """
    sshKeyIds: list[str] | None = None
    """
    A list of SSH key IDs to apply to the server on install (only valid for Linux/FreeBSD).
    """
    sshKeyIdsRefs: list[SshKeyIdsRef] | None = None
    """
    References to SSHKey in compute to populate sshKeyIds.
    """
    sshKeyIdsSelector: SshKeyIdsSelector | None = None
    """
    Selector for a list of SSHKey in compute to populate sshKeyIds.
    """
    tags: list[str] | None = None
    """
    A list of tags to apply to the instance.
    """
    userData: str | None = None
    """
    Generic data store, which some provisioning tools and cloud operating systems use as a configuration file. It is generally consumed only once after an instance has been launched, but individual needs may vary.
    """
    userScheme: str | None = None
    """
    The scheme used for the default user. Possible values are root or limited (linux servers only).
    """
    vpc2Ids: list[str] | None = None
    """
    (Deprecated) A list of VPC 2.0 IDs to be attached to the server.
    """
    vpcIds: list[str] | None = None
    """
    A list of VPC IDs to be attached to the server.
    """
    vpcIdsRefs: list[VpcIdsRef] | None = None
    """
    References to VPC in network to populate vpcIds.
    """
    vpcIdsSelector: VpcIdsSelector | None = None
    """
    Selector for a list of VPC in network to populate vpcIds.
    """
    vpcOnly: bool | None = None
    """
    If enabled, no public IP or NIC will be attached. Requires a vpc_ids with a NAT gateway set up.
    Requires a 'vpc_ids' with a NAT gateway attached
    """


class InitProvider(BaseModel):
    activationEmail: bool | None = None
    """
    Whether an activation email will be sent when the server is ready.
    """
    appId: int | None = None
    """
    The ID of the Vultr application to be installed on the server. See List Applications
    """
    appVariables: dict[str, str] | None = None
    """
    A map of user-supplied variable keys and values for Vultr Marketplace apps. See List Marketplace App Variables
    """
    backups: str | None = None
    """
    Whether automatic backups will be enabled for this server (these have an extra charge associated with them). Values can be enabled or disabled.
    """
    backupsSchedule: BackupsSchedule | None = None
    """
    A block that defines the way backups should be scheduled. While this is an optional field if backups are enabled this field is mandatory. The configuration of a backups_schedule is listed below.
    """
    blockDevices: list[BlockDevice] | None = None
    ddosProtection: bool | None = None
    """
    Whether DDOS protection will be enabled on the server (there is an additional charge for this).
    """
    disablePublicIpv4: bool | None = None
    """
    Whether the server has a public IPv4 address assigned (only possible with enable_ipv6 set to true)
    Don't set up a public IPv4 address when IPv6 is enabled.
    Will not do anything unless enable_ipv6 is also true.
    """
    enableIpv6: bool | None = None
    """
    Whether the server has IPv6 networking activated.
    """
    firewallGroupId: str | None = None
    """
    The ID of the firewall group to assign to the server.
    """
    firewallGroupIdRef: FirewallGroupIdRef | None = None
    """
    Reference to a FirewallGroup in network to populate firewallGroupId.
    """
    firewallGroupIdSelector: FirewallGroupIdSelector | None = None
    """
    Selector for a FirewallGroup in network to populate firewallGroupId.
    """
    hostname: str | None = None
    """
    The hostname to assign to the server.
    The hostname of the instance. Updating the
    hostname will cause a force new. This behavior is in place to prevent accidental reinstalls. Issuing an update to the
    hostname on UI or API issues a reinstall of the OS.
    """
    imageId: str | None = None
    """
    The ID of the Vultr marketplace application to be installed on the server. See List Applications Note marketplace applications are denoted by type: marketplace and you must use the image_id not the id.
    """
    ipxeChainUrl: str | None = None
    """
    The URL location of the iPXE chainloader.
    """
    isoId: str | None = None
    """
    The ID of the ISO file to be installed on the server. See List ISO
    """
    isoIdRef: IsoIdRef | None = None
    """
    Reference to a ISOPrivate in compute to populate isoId.
    """
    isoIdSelector: IsoIdSelector | None = None
    """
    Selector for a ISOPrivate in compute to populate isoId.
    """
    label: str | None = None
    """
    A label for the server.
    """
    osId: int | None = None
    """
    The ID of the operating system to be installed on the server. See List OS
    """
    plan: str | None = None
    """
    The ID of the plan that you want the instance to subscribe to. See List Plans
    """
    region: str | None = None
    """
    The ID of the region that the instance is to be created in. See List Regions
    """
    reservedIpId: str | None = None
    """
    ID of the floating IP to use as the main IP of this server.
    """
    reservedIpIdRef: ReservedIpIdRef | None = None
    """
    Reference to a ReservedIP in network to populate reservedIpId.
    """
    reservedIpIdSelector: ReservedIpIdSelector | None = None
    """
    Selector for a ReservedIP in network to populate reservedIpId.
    """
    scriptId: str | None = None
    """
    The ID of the startup script you want added to the server.
    """
    scriptIdRef: ScriptIdRef | None = None
    """
    Reference to a StartupScript in compute to populate scriptId.
    """
    scriptIdSelector: ScriptIdSelector | None = None
    """
    Selector for a StartupScript in compute to populate scriptId.
    """
    snapshotId: str | None = None
    """
    The ID of the Vultr snapshot that the server will restore for the initial installation. See List Snapshots
    """
    snapshotIdRef: SnapshotIdRef | None = None
    """
    Reference to a Snapshot in compute to populate snapshotId.
    """
    snapshotIdSelector: SnapshotIdSelector | None = None
    """
    Selector for a Snapshot in compute to populate snapshotId.
    """
    sshKeyIds: list[str] | None = None
    """
    A list of SSH key IDs to apply to the server on install (only valid for Linux/FreeBSD).
    """
    sshKeyIdsRefs: list[SshKeyIdsRef] | None = None
    """
    References to SSHKey in compute to populate sshKeyIds.
    """
    sshKeyIdsSelector: SshKeyIdsSelector | None = None
    """
    Selector for a list of SSHKey in compute to populate sshKeyIds.
    """
    tags: list[str] | None = None
    """
    A list of tags to apply to the instance.
    """
    userData: str | None = None
    """
    Generic data store, which some provisioning tools and cloud operating systems use as a configuration file. It is generally consumed only once after an instance has been launched, but individual needs may vary.
    """
    userScheme: str | None = None
    """
    The scheme used for the default user. Possible values are root or limited (linux servers only).
    """
    vpc2Ids: list[str] | None = None
    """
    (Deprecated) A list of VPC 2.0 IDs to be attached to the server.
    """
    vpcIds: list[str] | None = None
    """
    A list of VPC IDs to be attached to the server.
    """
    vpcIdsRefs: list[VpcIdsRef] | None = None
    """
    References to VPC in network to populate vpcIds.
    """
    vpcIdsSelector: VpcIdsSelector | None = None
    """
    Selector for a list of VPC in network to populate vpcIds.
    """
    vpcOnly: bool | None = None
    """
    If enabled, no public IP or NIC will be attached. Requires a vpc_ids with a NAT gateway set up.
    Requires a 'vpc_ids' with a NAT gateway attached
    """


class ProviderConfigRef(BaseModel):
    kind: str
    """
    Kind of the referenced object.
    """
    name: str
    """
    Name of the referenced object.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """


class Spec(BaseModel):
    forProvider: ForProvider
    initProvider: InitProvider | None = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'kind': 'ClusterProviderConfig', 'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class AtProvider(BaseModel):
    activationEmail: bool | None = None
    """
    Whether an activation email will be sent when the server is ready.
    """
    allowedBandwidth: int | None = None
    """
    The server's allowed bandwidth usage in GB.
    """
    appId: int | None = None
    """
    The ID of the Vultr application to be installed on the server. See List Applications
    """
    appVariables: dict[str, str] | None = None
    """
    A map of user-supplied variable keys and values for Vultr Marketplace apps. See List Marketplace App Variables
    """
    backups: str | None = None
    """
    Whether automatic backups will be enabled for this server (these have an extra charge associated with them). Values can be enabled or disabled.
    """
    backupsSchedule: BackupsSchedule | None = None
    """
    A block that defines the way backups should be scheduled. While this is an optional field if backups are enabled this field is mandatory. The configuration of a backups_schedule is listed below.
    """
    blockDevices: list[BlockDevice] | None = None
    dateCreated: str | None = None
    """
    The date the server was added to your Vultr account.
    """
    ddosProtection: bool | None = None
    """
    Whether DDOS protection will be enabled on the server (there is an additional charge for this).
    """
    disablePublicIpv4: bool | None = None
    """
    Whether the server has a public IPv4 address assigned (only possible with enable_ipv6 set to true)
    Don't set up a public IPv4 address when IPv6 is enabled.
    Will not do anything unless enable_ipv6 is also true.
    """
    disk: int | None = None
    """
    The description of the disk(s) on the server.
    """
    enableIpv6: bool | None = None
    """
    Whether the server has IPv6 networking activated.
    """
    features: list[str] | None = None
    """
    Array of which features are enabled.
    """
    firewallGroupId: str | None = None
    """
    The ID of the firewall group to assign to the server.
    """
    gatewayV4: str | None = None
    """
    The server's IPv4 gateway.
    """
    hostname: str | None = None
    """
    The hostname to assign to the server.
    The hostname of the instance. Updating the
    hostname will cause a force new. This behavior is in place to prevent accidental reinstalls. Issuing an update to the
    hostname on UI or API issues a reinstall of the OS.
    """
    id: str | None = None
    """
    ID of the server.
    """
    imageId: str | None = None
    """
    The ID of the Vultr marketplace application to be installed on the server. See List Applications Note marketplace applications are denoted by type: marketplace and you must use the image_id not the id.
    """
    internalIp: str | None = None
    """
    The server's internal IP address.
    """
    ipxeChainUrl: str | None = None
    """
    The URL location of the iPXE chainloader.
    """
    isoId: str | None = None
    """
    The ID of the ISO file to be installed on the server. See List ISO
    """
    label: str | None = None
    """
    A label for the server.
    """
    mainIp: str | None = None
    """
    The server's main IP address.
    """
    netmaskV4: str | None = None
    """
    The server's IPv4 netmask.
    """
    os: str | None = None
    """
    The string description of the operating system installed on the server.
    """
    osId: int | None = None
    """
    The ID of the operating system to be installed on the server. See List OS
    """
    plan: str | None = None
    """
    The ID of the plan that you want the instance to subscribe to. See List Plans
    """
    powerStatus: str | None = None
    """
    Whether the server is powered on or not.
    """
    ram: int | None = None
    """
    The amount of memory available on the server in MB.
    """
    region: str | None = None
    """
    The ID of the region that the instance is to be created in. See List Regions
    """
    reservedIpId: str | None = None
    """
    ID of the floating IP to use as the main IP of this server.
    """
    scriptId: str | None = None
    """
    The ID of the startup script you want added to the server.
    """
    serverStatus: str | None = None
    """
    A more detailed server status (none, locked, installingbooting, isomounting, ok).
    """
    snapshotId: str | None = None
    """
    The ID of the Vultr snapshot that the server will restore for the initial installation. See List Snapshots
    """
    sshKeyIds: list[str] | None = None
    """
    A list of SSH key IDs to apply to the server on install (only valid for Linux/FreeBSD).
    """
    status: str | None = None
    """
    The status of the server's subscription.
    """
    tags: list[str] | None = None
    """
    A list of tags to apply to the instance.
    """
    userData: str | None = None
    """
    Generic data store, which some provisioning tools and cloud operating systems use as a configuration file. It is generally consumed only once after an instance has been launched, but individual needs may vary.
    """
    userScheme: str | None = None
    """
    The scheme used for the default user. Possible values are root or limited (linux servers only).
    """
    v6MainIp: str | None = None
    """
    The main IPv6 network address.
    """
    v6Network: str | None = None
    """
    The IPv6 subnet.
    """
    v6NetworkSize: int | None = None
    """
    The IPv6 network size in bits.
    """
    vcpuCount: int | None = None
    """
    The number of virtual CPUs available on the server.
    """
    vpc2Ids: list[str] | None = None
    """
    (Deprecated) A list of VPC 2.0 IDs to be attached to the server.
    """
    vpcIds: list[str] | None = None
    """
    A list of VPC IDs to be attached to the server.
    """
    vpcOnly: bool | None = None
    """
    If enabled, no public IP or NIC will be attached. Requires a vpc_ids with a NAT gateway set up.
    Requires a 'vpc_ids' with a NAT gateway attached
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    lastHandledReconcileAt: str | None = None
    """
    LastHandledReconcileAt holds the value of the most recent
    reconcile-requested-at annotation token that the controller has
    processed. Users can compare this to the annotation to determine
    whether a reconcile request has been handled.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class Instance(BaseModel):
    apiVersion: Literal['compute.vultr.m.upbound.io/v1beta1'] | None = (
        'compute.vultr.m.upbound.io/v1beta1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['Instance'] | None = 'Instance'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    InstanceSpec defines the desired state of Instance
    """
    status: Status | None = None
    """
    InstanceStatus defines the observed state of Instance.
    """


class InstanceList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[Instance]
    """
    List of instances. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """