# generated by datamodel-codegen:
#   filename:  workdir/network_vultr_upbound_io_v1beta1_loadbalancer.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from .....k8s.apimachinery.pkg.apis.meta import v1


class FirewallRule(BaseModel):
    ipType: str | None = None
    """
    The type of ip this rule is - may be either v4 or v6.
    """
    port: int | None = None
    """
    The assigned port (integer) on the attached instances that the load balancer should check against. Default value is 80.
    """
    source: str | None = None
    """
    IP address with subnet that is allowed through the firewall. You may also pass in cloudflare which will allow only CloudFlares IP range.
    """


class ForwardingRule(BaseModel):
    backendPort: int | None = None
    """
    Port on instance side.
    """
    backendProtocol: str | None = None
    """
    Protocol on instance side. Possible values: "http", "https", "tcp".
    """
    frontendPort: int | None = None
    """
    Port on load balancer side.
    """
    frontendProtocol: str | None = None
    """
    Protocol on load balancer side. Possible values: "http", "https", "tcp".
    """


class HealthCheck(BaseModel):
    checkInterval: int | None = None
    """
    Time in seconds to perform health check. Default value is 15.
    """
    healthyThreshold: int | None = None
    """
    Number of failed attempts encountered before failover. Default value is 5.
    """
    path: str | None = None
    """
    The path on the attached instances that the load balancer should check against. Default value is /
    """
    port: int | None = None
    """
    The assigned port (integer) on the attached instances that the load balancer should check against. Default value is 80.
    """
    protocol: str | None = None
    """
    The protocol used to traffic requests to the load balancer. Possible values are http, or tcp. Default value is http.
    """
    responseTimeout: int | None = None
    """
    Time in seconds to wait for a health check response. Default value is 5.
    """
    unhealthyThreshold: int | None = None
    """
    Number of failed attempts encountered before failover. Default value is 5.
    """


class PrivateKeySecretRef(BaseModel):
    key: str
    """
    The key to select.
    """
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class Ssl(BaseModel):
    certificate: str | None = None
    """
    The SSL Certificate.
    """
    chain: str | None = None
    """
    The SSL certificate chain.
    """
    privateKeySecretRef: PrivateKeySecretRef | None = None
    """
    The SSL certificates private key.
    """


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class VpcRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class VpcSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ForProvider(BaseModel):
    attachedInstances: list[str] | None = None
    """
    Array of instances that are currently attached to the load balancer.
    """
    autoSslDomain: str | None = None
    """
    The auto SSL domain configuration for a load balancer. This can be a root domain (example.com) or include a subdomain (sub.example.com).
    """
    balancingAlgorithm: str | None = None
    """
    The balancing algorithm for your load balancer. Options are roundrobin or leastconn. Default value is roundrobin
    """
    cookieName: str | None = None
    """
    Name for your given sticky session.
    """
    firewallRules: list[FirewallRule] | None = None
    """
    Defines the firewall rules for a load balancer.
    """
    forwardingRules: list[ForwardingRule] | None = None
    """
    List of forwarding rules for a load balancer. The configuration of a forwarding_rules is listened below.
    """
    globalRegions: list[str] | None = None
    """
    A set of region IDs to deploy child load balancers to.
    """
    healthCheck: HealthCheck | None = None
    """
    A block that defines the way load balancers should check for health. The configuration of a health_check is listed below.
    """
    httpVersion: int | None = None
    """
    Integer value that indicates if HTTP/2 or HTTP/3 is enabled. Allowed values 2 or 3.
    """
    label: str | None = None
    """
    The load balancer's label.
    """
    nodes: int | None = None
    """
    The number of nodes to add to the load balancer (1-99). Must be an odd number. Default value is 1.
    """
    proxyProtocol: bool | None = None
    """
    Boolean value that indicates if Proxy Protocol is enabled.
    """
    region: str | None = None
    """
    The region your load balancer is deployed in.
    """
    ssl: Ssl | None = None
    """
    A block that supplies your ssl configuration to be used with HTTPS. The configuration of a ssl is listed below.
    """
    sslRedirect: bool | None = None
    """
    Boolean value that indicates if HTTP calls will be redirected to HTTPS.
    """
    vpc: str | None = None
    """
    A VPC ID that the load balancer should be attached to.
    """
    vpcRef: VpcRef | None = None
    """
    Reference to a VPC in network to populate vpc.
    """
    vpcSelector: VpcSelector | None = None
    """
    Selector for a VPC in network to populate vpc.
    """


class SslModel(BaseModel):
    certificate: str | None = None
    """
    The SSL Certificate.
    """
    chain: str | None = None
    """
    The SSL certificate chain.
    """
    privateKeySecretRef: PrivateKeySecretRef
    """
    The SSL certificates private key.
    """


class InitProvider(BaseModel):
    attachedInstances: list[str] | None = None
    """
    Array of instances that are currently attached to the load balancer.
    """
    autoSslDomain: str | None = None
    """
    The auto SSL domain configuration for a load balancer. This can be a root domain (example.com) or include a subdomain (sub.example.com).
    """
    balancingAlgorithm: str | None = None
    """
    The balancing algorithm for your load balancer. Options are roundrobin or leastconn. Default value is roundrobin
    """
    cookieName: str | None = None
    """
    Name for your given sticky session.
    """
    firewallRules: list[FirewallRule] | None = None
    """
    Defines the firewall rules for a load balancer.
    """
    forwardingRules: list[ForwardingRule] | None = None
    """
    List of forwarding rules for a load balancer. The configuration of a forwarding_rules is listened below.
    """
    globalRegions: list[str] | None = None
    """
    A set of region IDs to deploy child load balancers to.
    """
    healthCheck: HealthCheck | None = None
    """
    A block that defines the way load balancers should check for health. The configuration of a health_check is listed below.
    """
    httpVersion: int | None = None
    """
    Integer value that indicates if HTTP/2 or HTTP/3 is enabled. Allowed values 2 or 3.
    """
    label: str | None = None
    """
    The load balancer's label.
    """
    nodes: int | None = None
    """
    The number of nodes to add to the load balancer (1-99). Must be an odd number. Default value is 1.
    """
    proxyProtocol: bool | None = None
    """
    Boolean value that indicates if Proxy Protocol is enabled.
    """
    region: str | None = None
    """
    The region your load balancer is deployed in.
    """
    ssl: SslModel | None = None
    """
    A block that supplies your ssl configuration to be used with HTTPS. The configuration of a ssl is listed below.
    """
    sslRedirect: bool | None = None
    """
    Boolean value that indicates if HTTP calls will be redirected to HTTPS.
    """
    vpc: str | None = None
    """
    A VPC ID that the load balancer should be attached to.
    """
    vpcRef: VpcRef | None = None
    """
    Reference to a VPC in network to populate vpc.
    """
    vpcSelector: VpcSelector | None = None
    """
    Selector for a VPC in network to populate vpc.
    """


class ProviderConfigRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class Spec(BaseModel):
    deletionPolicy: Literal['Orphan', 'Delete'] | None = 'Delete'
    """
    DeletionPolicy specifies what will happen to the underlying external
    when this managed resource is deleted - either "Delete" or "Orphan" the
    external resource.
    This field is planned to be deprecated in favor of the ManagementPolicies
    field in a future release. Currently, both could be set independently and
    non-default values would be honored if the feature flag is enabled.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    """
    forProvider: ForProvider
    initProvider: InitProvider | None = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    This field is planned to replace the DeletionPolicy field in a future
    release. Currently, both could be set independently and non-default
    values would be honored if the feature flag is enabled. If both are
    custom, the DeletionPolicy field will be ignored.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class FirewallRuleModel(BaseModel):
    id: str | None = None
    """
    The load balancer ID.
    """
    ipType: str | None = None
    """
    The type of ip this rule is - may be either v4 or v6.
    """
    port: int | None = None
    """
    The assigned port (integer) on the attached instances that the load balancer should check against. Default value is 80.
    """
    source: str | None = None
    """
    IP address with subnet that is allowed through the firewall. You may also pass in cloudflare which will allow only CloudFlares IP range.
    """


class ForwardingRuleModel(BaseModel):
    backendPort: int | None = None
    """
    Port on instance side.
    """
    backendProtocol: str | None = None
    """
    Protocol on instance side. Possible values: "http", "https", "tcp".
    """
    frontendPort: int | None = None
    """
    Port on load balancer side.
    """
    frontendProtocol: str | None = None
    """
    Protocol on load balancer side. Possible values: "http", "https", "tcp".
    """
    ruleId: str | None = None
    """
    The load balancer ID.
    """


class SslModel1(BaseModel):
    certificate: str | None = None
    """
    The SSL Certificate.
    """
    chain: str | None = None
    """
    The SSL certificate chain.
    """


class AtProvider(BaseModel):
    attachedInstances: list[str] | None = None
    """
    Array of instances that are currently attached to the load balancer.
    """
    autoSslDomain: str | None = None
    """
    The auto SSL domain configuration for a load balancer. This can be a root domain (example.com) or include a subdomain (sub.example.com).
    """
    balancingAlgorithm: str | None = None
    """
    The balancing algorithm for your load balancer. Options are roundrobin or leastconn. Default value is roundrobin
    """
    cookieName: str | None = None
    """
    Name for your given sticky session.
    """
    firewallRules: list[FirewallRuleModel] | None = None
    """
    Defines the firewall rules for a load balancer.
    """
    forwardingRules: list[ForwardingRuleModel] | None = None
    """
    List of forwarding rules for a load balancer. The configuration of a forwarding_rules is listened below.
    """
    globalRegions: list[str] | None = None
    """
    A set of region IDs to deploy child load balancers to.
    """
    hasSsl: bool | None = None
    """
    Boolean value that indicates if SSL is enabled.
    """
    healthCheck: HealthCheck | None = None
    """
    A block that defines the way load balancers should check for health. The configuration of a health_check is listed below.
    """
    httpVersion: int | None = None
    """
    Integer value that indicates if HTTP/2 or HTTP/3 is enabled. Allowed values 2 or 3.
    """
    id: str | None = None
    """
    The load balancer ID.
    """
    ipv4: str | None = None
    """
    IPv4 address for your load balancer.
    """
    ipv6: str | None = None
    """
    IPv6 address for your load balancer.
    """
    label: str | None = None
    """
    The load balancer's label.
    """
    nodes: int | None = None
    """
    The number of nodes to add to the load balancer (1-99). Must be an odd number. Default value is 1.
    """
    proxyProtocol: bool | None = None
    """
    Boolean value that indicates if Proxy Protocol is enabled.
    """
    region: str | None = None
    """
    The region your load balancer is deployed in.
    """
    ssl: SslModel1 | None = None
    """
    A block that supplies your ssl configuration to be used with HTTPS. The configuration of a ssl is listed below.
    """
    sslRedirect: bool | None = None
    """
    Boolean value that indicates if HTTP calls will be redirected to HTTPS.
    """
    status: str | None = None
    """
    Current status for the load balancer
    """
    vpc: str | None = None
    """
    A VPC ID that the load balancer should be attached to.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    lastHandledReconcileAt: str | None = None
    """
    LastHandledReconcileAt holds the value of the most recent
    reconcile-requested-at annotation token that the controller has
    processed. Users can compare this to the annotation to determine
    whether a reconcile request has been handled.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class LoadBalancer(BaseModel):
    apiVersion: Literal['network.vultr.upbound.io/v1beta1'] | None = (
        'network.vultr.upbound.io/v1beta1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['LoadBalancer'] | None = 'LoadBalancer'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    LoadBalancerSpec defines the desired state of LoadBalancer
    """
    status: Status | None = None
    """
    LoadBalancerStatus defines the observed state of LoadBalancer.
    """


class LoadBalancerList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[LoadBalancer]
    """
    List of loadbalancers. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """