# generated by datamodel-codegen:
#   filename:  workdir/network_vultr_upbound_io_v1beta1_firewallrule.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from .....k8s.apimachinery.pkg.apis.meta import v1


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class FirewallGroupIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class FirewallGroupIdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ForProvider(BaseModel):
    firewallGroupId: str | None = None
    """
    The firewall group that the firewall rule will belong to.
    """
    firewallGroupIdRef: FirewallGroupIdRef | None = None
    """
    Reference to a FirewallGroup in network to populate firewallGroupId.
    """
    firewallGroupIdSelector: FirewallGroupIdSelector | None = None
    """
    Selector for a FirewallGroup in network to populate firewallGroupId.
    """
    ipType: str | None = None
    """
    The type of ip for this firewall rule. Possible values (v4, v6) Note they must be lowercase
    """
    notes: str | None = None
    """
    A simple note for a given firewall rule
    """
    port: str | None = None
    """
    TCP/UDP only. This field can be a specific port or a colon separated port range.
    """
    protocol: str | None = None
    """
    The type of protocol for this firewall rule. Possible values (icmp, tcp, udp, gre, esp, ah) Note they must be lowercase
    """
    source: str | None = None
    """
    Possible values ("", cloudflare)
    """
    subnet: str | None = None
    """
    IP address that you want to define for this firewall rule.
    """
    subnetSize: int | None = None
    """
    The number of bits for the subnet in CIDR notation. Example: 32.
    """


class InitProvider(BaseModel):
    firewallGroupId: str | None = None
    """
    The firewall group that the firewall rule will belong to.
    """
    firewallGroupIdRef: FirewallGroupIdRef | None = None
    """
    Reference to a FirewallGroup in network to populate firewallGroupId.
    """
    firewallGroupIdSelector: FirewallGroupIdSelector | None = None
    """
    Selector for a FirewallGroup in network to populate firewallGroupId.
    """
    ipType: str | None = None
    """
    The type of ip for this firewall rule. Possible values (v4, v6) Note they must be lowercase
    """
    notes: str | None = None
    """
    A simple note for a given firewall rule
    """
    port: str | None = None
    """
    TCP/UDP only. This field can be a specific port or a colon separated port range.
    """
    protocol: str | None = None
    """
    The type of protocol for this firewall rule. Possible values (icmp, tcp, udp, gre, esp, ah) Note they must be lowercase
    """
    source: str | None = None
    """
    Possible values ("", cloudflare)
    """
    subnet: str | None = None
    """
    IP address that you want to define for this firewall rule.
    """
    subnetSize: int | None = None
    """
    The number of bits for the subnet in CIDR notation. Example: 32.
    """


class ProviderConfigRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class Spec(BaseModel):
    deletionPolicy: Literal['Orphan', 'Delete'] | None = 'Delete'
    """
    DeletionPolicy specifies what will happen to the underlying external
    when this managed resource is deleted - either "Delete" or "Orphan" the
    external resource.
    This field is planned to be deprecated in favor of the ManagementPolicies
    field in a future release. Currently, both could be set independently and
    non-default values would be honored if the feature flag is enabled.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    """
    forProvider: ForProvider
    initProvider: InitProvider | None = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    This field is planned to replace the DeletionPolicy field in a future
    release. Currently, both could be set independently and non-default
    values would be honored if the feature flag is enabled. If both are
    custom, the DeletionPolicy field will be ignored.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class AtProvider(BaseModel):
    firewallGroupId: str | None = None
    """
    The firewall group that the firewall rule will belong to.
    """
    id: str | None = None
    """
    The given ID for a firewall rule.
    """
    ipType: str | None = None
    """
    The type of ip for this firewall rule. Possible values (v4, v6) Note they must be lowercase
    """
    notes: str | None = None
    """
    A simple note for a given firewall rule
    """
    port: str | None = None
    """
    TCP/UDP only. This field can be a specific port or a colon separated port range.
    """
    protocol: str | None = None
    """
    The type of protocol for this firewall rule. Possible values (icmp, tcp, udp, gre, esp, ah) Note they must be lowercase
    """
    source: str | None = None
    """
    Possible values ("", cloudflare)
    """
    subnet: str | None = None
    """
    IP address that you want to define for this firewall rule.
    """
    subnetSize: int | None = None
    """
    The number of bits for the subnet in CIDR notation. Example: 32.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    lastHandledReconcileAt: str | None = None
    """
    LastHandledReconcileAt holds the value of the most recent
    reconcile-requested-at annotation token that the controller has
    processed. Users can compare this to the annotation to determine
    whether a reconcile request has been handled.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class FirewallRule(BaseModel):
    apiVersion: Literal['network.vultr.upbound.io/v1beta1'] | None = (
        'network.vultr.upbound.io/v1beta1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['FirewallRule'] | None = 'FirewallRule'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    FirewallRuleSpec defines the desired state of FirewallRule
    """
    status: Status | None = None
    """
    FirewallRuleStatus defines the observed state of FirewallRule.
    """


class FirewallRuleList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[FirewallRule]
    """
    List of firewallrules. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """