# generated by datamodel-codegen:
#   filename:  workdir/database_vultr_upbound_io_v1beta1_replica.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from .....k8s.apimachinery.pkg.apis.meta import v1


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class DatabaseIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class DatabaseIdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class FerretdbCredentialsSecretRef(BaseModel):
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class ForProvider(BaseModel):
    backupHour: str | None = None
    """
    The preferred hour of the day (UTC) for daily backups to take place (unavailable for Kafka engine types).
    """
    backupMinute: str | None = None
    """
    The preferred minute of the backup hour for daily backups to take place (unavailable for Kafka engine types).
    """
    databaseId: str | None = None
    """
    The managed database ID you want to attach this replica to.
    """
    databaseIdRef: DatabaseIdRef | None = None
    """
    Reference to a Database in database to populate databaseId.
    """
    databaseIdSelector: DatabaseIdSelector | None = None
    """
    Selector for a Database in database to populate databaseId.
    """
    evictionPolicy: str | None = None
    """
    The configuration value for the data eviction policy on the managed database read replica (Valkey engine types only).
    """
    ferretdbCredentialsSecretRef: FerretdbCredentialsSecretRef | None = None
    """
    A SecretReference is a reference to a secret in an arbitrary namespace.
    """
    label: str | None = None
    """
    A label for the managed database read replica.
    """
    mysqlLongQueryTime: int | None = None
    """
    The configuration value for the long query time (in seconds) on the managed database read replica (MySQL engine types only).
    """
    mysqlRequirePrimaryKey: bool | None = None
    """
    The configuration value for whether primary keys are required on the managed database read replica (MySQL engine types only).
    """
    mysqlSlowQueryLog: bool | None = None
    """
    The configuration value for slow query logging on the managed database read replica (MySQL engine types only).
    """
    mysqlSqlModes: list[str] | None = None
    """
    A list of SQL modes currently configured for the managed database read replica (MySQL engine types only).
    """
    planDisk: int | None = None
    """
    The description of the disk(s) on the managed database read replica.
    """
    publicHost: str | None = None
    """
    The public hostname assigned to the managed database read replica (VPC-attached only).
    """
    region: str | None = None
    """
    The ID of the region that the managed database read replica is to be created in. See List Regions
    """
    tag: str | None = None
    """
    The tag to assign to the managed database read replica.
    """
    trustedIps: list[str] | None = None
    """
    A list of allowed IP addresses for the managed database read replica.
    """


class InitProvider(BaseModel):
    backupHour: str | None = None
    """
    The preferred hour of the day (UTC) for daily backups to take place (unavailable for Kafka engine types).
    """
    backupMinute: str | None = None
    """
    The preferred minute of the backup hour for daily backups to take place (unavailable for Kafka engine types).
    """
    databaseId: str | None = None
    """
    The managed database ID you want to attach this replica to.
    """
    databaseIdRef: DatabaseIdRef | None = None
    """
    Reference to a Database in database to populate databaseId.
    """
    databaseIdSelector: DatabaseIdSelector | None = None
    """
    Selector for a Database in database to populate databaseId.
    """
    evictionPolicy: str | None = None
    """
    The configuration value for the data eviction policy on the managed database read replica (Valkey engine types only).
    """
    ferretdbCredentialsSecretRef: dict[str, str] | None = None
    label: str | None = None
    """
    A label for the managed database read replica.
    """
    mysqlLongQueryTime: int | None = None
    """
    The configuration value for the long query time (in seconds) on the managed database read replica (MySQL engine types only).
    """
    mysqlRequirePrimaryKey: bool | None = None
    """
    The configuration value for whether primary keys are required on the managed database read replica (MySQL engine types only).
    """
    mysqlSlowQueryLog: bool | None = None
    """
    The configuration value for slow query logging on the managed database read replica (MySQL engine types only).
    """
    mysqlSqlModes: list[str] | None = None
    """
    A list of SQL modes currently configured for the managed database read replica (MySQL engine types only).
    """
    planDisk: int | None = None
    """
    The description of the disk(s) on the managed database read replica.
    """
    publicHost: str | None = None
    """
    The public hostname assigned to the managed database read replica (VPC-attached only).
    """
    region: str | None = None
    """
    The ID of the region that the managed database read replica is to be created in. See List Regions
    """
    tag: str | None = None
    """
    The tag to assign to the managed database read replica.
    """
    trustedIps: list[str] | None = None
    """
    A list of allowed IP addresses for the managed database read replica.
    """


class ProviderConfigRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class Spec(BaseModel):
    deletionPolicy: Literal['Orphan', 'Delete'] | None = 'Delete'
    """
    DeletionPolicy specifies what will happen to the underlying external
    when this managed resource is deleted - either "Delete" or "Orphan" the
    external resource.
    This field is planned to be deprecated in favor of the ManagementPolicies
    field in a future release. Currently, both could be set independently and
    non-default values would be honored if the feature flag is enabled.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    """
    forProvider: ForProvider
    initProvider: InitProvider | None = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    This field is planned to replace the DeletionPolicy field in a future
    release. Currently, both could be set independently and non-default
    values would be honored if the feature flag is enabled. If both are
    custom, the DeletionPolicy field will be ignored.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class AtProvider(BaseModel):
    backupHour: str | None = None
    """
    The preferred hour of the day (UTC) for daily backups to take place (unavailable for Kafka engine types).
    """
    backupMinute: str | None = None
    """
    The preferred minute of the backup hour for daily backups to take place (unavailable for Kafka engine types).
    """
    caCertificate: str | None = None
    """
    The CA certificate for Managed Databases on this account.
    """
    clusterTimeZone: str | None = None
    """
    The configured time zone for the managed database read replica in TZ database format.
    """
    databaseEngine: str | None = None
    """
    The database engine of the managed database read replica.
    """
    databaseEngineVersion: str | None = None
    """
    The database engine version of the managed database read replica.
    """
    databaseId: str | None = None
    """
    The managed database ID you want to attach this replica to.
    """
    dateCreated: str | None = None
    """
    The date the managed database read replica was added to your Vultr account.
    """
    dbname: str | None = None
    """
    The managed database read replica's default logical database.
    """
    evictionPolicy: str | None = None
    """
    The configuration value for the data eviction policy on the managed database read replica (Valkey engine types only).
    """
    host: str | None = None
    """
    The hostname assigned to the managed database read replica.
    """
    id: str | None = None
    """
    The ID of the managed database read replica.
    """
    label: str | None = None
    """
    A label for the managed database read replica.
    """
    latestBackup: str | None = None
    """
    The date of the latest backup available on the managed database read replica.
    """
    maintenanceDow: str | None = None
    """
    The preferred maintenance day of week for the managed database read replica.
    """
    maintenanceTime: str | None = None
    """
    The preferred maintenance time for the managed database read replica.
    """
    mysqlLongQueryTime: int | None = None
    """
    The configuration value for the long query time (in seconds) on the managed database read replica (MySQL engine types only).
    """
    mysqlRequirePrimaryKey: bool | None = None
    """
    The configuration value for whether primary keys are required on the managed database read replica (MySQL engine types only).
    """
    mysqlSlowQueryLog: bool | None = None
    """
    The configuration value for slow query logging on the managed database read replica (MySQL engine types only).
    """
    mysqlSqlModes: list[str] | None = None
    """
    A list of SQL modes currently configured for the managed database read replica (MySQL engine types only).
    """
    plan: str | None = None
    """
    The managed database read replica's plan ID.
    """
    planDisk: int | None = None
    """
    The description of the disk(s) on the managed database read replica.
    """
    planRam: int | None = None
    """
    The amount of memory available on the managed database read replica in MB.
    """
    planReplicas: int | None = None
    """
    The number of standby nodes available on the managed database read replica.
    """
    planVcpus: int | None = None
    """
    The number of virtual CPUs available on the managed database read replica.
    """
    port: str | None = None
    """
    The connection port for the managed database read replica.
    """
    publicHost: str | None = None
    """
    The public hostname assigned to the managed database read replica (VPC-attached only).
    """
    region: str | None = None
    """
    The ID of the region that the managed database read replica is to be created in. See List Regions
    """
    status: str | None = None
    """
    The current status of the managed database read replica (poweroff, rebuilding, rebalancing, configuring, running).
    """
    tag: str | None = None
    """
    The tag to assign to the managed database read replica.
    """
    trustedIps: list[str] | None = None
    """
    A list of allowed IP addresses for the managed database read replica.
    """
    user: str | None = None
    """
    The primary admin user for the managed database read replica.
    """
    vpcId: str | None = None
    """
    The ID of the VPC Network attached to the managed database read replica.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    lastHandledReconcileAt: str | None = None
    """
    LastHandledReconcileAt holds the value of the most recent
    reconcile-requested-at annotation token that the controller has
    processed. Users can compare this to the annotation to determine
    whether a reconcile request has been handled.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class Replica(BaseModel):
    apiVersion: Literal['database.vultr.upbound.io/v1beta1'] | None = (
        'database.vultr.upbound.io/v1beta1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['Replica'] | None = 'Replica'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    ReplicaSpec defines the desired state of Replica
    """
    status: Status | None = None
    """
    ReplicaStatus defines the observed state of Replica.
    """


class ReplicaList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[Replica]
    """
    List of replicas. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """