# generated by datamodel-codegen:
#   filename:  workdir/compute_vultr_upbound_io_v1beta1_baremetalserver.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from .....k8s.apimachinery.pkg.apis.meta import v1


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class ScriptIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class ScriptIdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class SnapshotIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class SnapshotIdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class SshKeyIdsRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class SshKeyIdsSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class VpcIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class VpcIdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ForProvider(BaseModel):
    activationEmail: bool | None = None
    """
    Whether an activation email will be sent when the server is ready.
    """
    appId: int | None = None
    """
    The ID of the Vultr application to be installed on the server. See List Applications
    """
    appVariables: dict[str, str] | None = None
    """
    A map of user-supplied variable keys and values for Vultr Marketplace apps. See List Marketplace App Variables
    """
    enableIpv6: bool | None = None
    """
    Whether the server has IPv6 networking activated.
    """
    hostname: str | None = None
    """
    The hostname to assign to the server.
    """
    imageId: str | None = None
    """
    The ID of the Vultr marketplace application to be installed on the server. See List Applications Note marketplace applications are denoted by type: marketplace and you must use the image_id not the id.
    """
    label: str | None = None
    """
    A label for the server.
    """
    mdiskMode: str | None = None
    """
    The raid configuration to use when provisioning the server.  Possible values: raid1, jbod, none. Defaults to none.
    """
    osId: int | None = None
    """
    The ID of the operating system to be installed on the server. See List OS
    """
    persistentPxe: bool | None = None
    plan: str | None = None
    """
    The ID of the plan that you want the server to subscribe to. See List Plans
    """
    region: str | None = None
    """
    The ID of the region that the server is to be created in. See List Regions
    """
    reservedIpv4: str | None = None
    """
    The ID of the floating IP to use as the main IP of this server. See Reserved IPs
    """
    scriptId: str | None = None
    """
    The ID of the startup script you want added to the server.
    """
    scriptIdRef: ScriptIdRef | None = None
    """
    Reference to a StartupScript in compute to populate scriptId.
    """
    scriptIdSelector: ScriptIdSelector | None = None
    """
    Selector for a StartupScript in compute to populate scriptId.
    """
    snapshotId: str | None = None
    """
    The ID of the Vultr snapshot that the server will restore for the initial installation. See List Snapshots
    """
    snapshotIdRef: SnapshotIdRef | None = None
    """
    Reference to a Snapshot in compute to populate snapshotId.
    """
    snapshotIdSelector: SnapshotIdSelector | None = None
    """
    Selector for a Snapshot in compute to populate snapshotId.
    """
    sshKeyIds: list[str] | None = None
    """
    A list of SSH key IDs to apply to the server on install (only valid for Linux/FreeBSD).
    """
    sshKeyIdsRefs: list[SshKeyIdsRef] | None = None
    """
    References to SSHKey in compute to populate sshKeyIds.
    """
    sshKeyIdsSelector: SshKeyIdsSelector | None = None
    """
    Selector for a list of SSHKey in compute to populate sshKeyIds.
    """
    tags: list[str] | None = None
    """
    A list of tags to apply to the servier.
    """
    userData: str | None = None
    """
    Generic data store, which some provisioning tools and cloud operating systems use as a configuration file. It is generally consumed only once after an instance has been launched, but individual needs may vary.
    """
    userScheme: str | None = None
    """
    The scheme used for the default user. Possible values are root or limited (linux servers only).
    """
    vpc2Ids: list[str] | None = None
    """
    (Deprecated) A list of VPC 2.0 IDs to be attached to the server.
    """
    vpcId: str | None = None
    """
    The VPC ID to use when creating the server.
    """
    vpcIdRef: VpcIdRef | None = None
    """
    Reference to a VPC in network to populate vpcId.
    """
    vpcIdSelector: VpcIdSelector | None = None
    """
    Selector for a VPC in network to populate vpcId.
    """


class InitProvider(BaseModel):
    activationEmail: bool | None = None
    """
    Whether an activation email will be sent when the server is ready.
    """
    appId: int | None = None
    """
    The ID of the Vultr application to be installed on the server. See List Applications
    """
    appVariables: dict[str, str] | None = None
    """
    A map of user-supplied variable keys and values for Vultr Marketplace apps. See List Marketplace App Variables
    """
    enableIpv6: bool | None = None
    """
    Whether the server has IPv6 networking activated.
    """
    hostname: str | None = None
    """
    The hostname to assign to the server.
    """
    imageId: str | None = None
    """
    The ID of the Vultr marketplace application to be installed on the server. See List Applications Note marketplace applications are denoted by type: marketplace and you must use the image_id not the id.
    """
    label: str | None = None
    """
    A label for the server.
    """
    mdiskMode: str | None = None
    """
    The raid configuration to use when provisioning the server.  Possible values: raid1, jbod, none. Defaults to none.
    """
    osId: int | None = None
    """
    The ID of the operating system to be installed on the server. See List OS
    """
    persistentPxe: bool | None = None
    plan: str | None = None
    """
    The ID of the plan that you want the server to subscribe to. See List Plans
    """
    region: str | None = None
    """
    The ID of the region that the server is to be created in. See List Regions
    """
    reservedIpv4: str | None = None
    """
    The ID of the floating IP to use as the main IP of this server. See Reserved IPs
    """
    scriptId: str | None = None
    """
    The ID of the startup script you want added to the server.
    """
    scriptIdRef: ScriptIdRef | None = None
    """
    Reference to a StartupScript in compute to populate scriptId.
    """
    scriptIdSelector: ScriptIdSelector | None = None
    """
    Selector for a StartupScript in compute to populate scriptId.
    """
    snapshotId: str | None = None
    """
    The ID of the Vultr snapshot that the server will restore for the initial installation. See List Snapshots
    """
    snapshotIdRef: SnapshotIdRef | None = None
    """
    Reference to a Snapshot in compute to populate snapshotId.
    """
    snapshotIdSelector: SnapshotIdSelector | None = None
    """
    Selector for a Snapshot in compute to populate snapshotId.
    """
    sshKeyIds: list[str] | None = None
    """
    A list of SSH key IDs to apply to the server on install (only valid for Linux/FreeBSD).
    """
    sshKeyIdsRefs: list[SshKeyIdsRef] | None = None
    """
    References to SSHKey in compute to populate sshKeyIds.
    """
    sshKeyIdsSelector: SshKeyIdsSelector | None = None
    """
    Selector for a list of SSHKey in compute to populate sshKeyIds.
    """
    tags: list[str] | None = None
    """
    A list of tags to apply to the servier.
    """
    userData: str | None = None
    """
    Generic data store, which some provisioning tools and cloud operating systems use as a configuration file. It is generally consumed only once after an instance has been launched, but individual needs may vary.
    """
    userScheme: str | None = None
    """
    The scheme used for the default user. Possible values are root or limited (linux servers only).
    """
    vpc2Ids: list[str] | None = None
    """
    (Deprecated) A list of VPC 2.0 IDs to be attached to the server.
    """
    vpcId: str | None = None
    """
    The VPC ID to use when creating the server.
    """
    vpcIdRef: VpcIdRef | None = None
    """
    Reference to a VPC in network to populate vpcId.
    """
    vpcIdSelector: VpcIdSelector | None = None
    """
    Selector for a VPC in network to populate vpcId.
    """


class ProviderConfigRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class Spec(BaseModel):
    deletionPolicy: Literal['Orphan', 'Delete'] | None = 'Delete'
    """
    DeletionPolicy specifies what will happen to the underlying external
    when this managed resource is deleted - either "Delete" or "Orphan" the
    external resource.
    This field is planned to be deprecated in favor of the ManagementPolicies
    field in a future release. Currently, both could be set independently and
    non-default values would be honored if the feature flag is enabled.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    """
    forProvider: ForProvider
    initProvider: InitProvider | None = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    This field is planned to replace the DeletionPolicy field in a future
    release. Currently, both could be set independently and non-default
    values would be honored if the feature flag is enabled. If both are
    custom, the DeletionPolicy field will be ignored.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class AtProvider(BaseModel):
    activationEmail: bool | None = None
    """
    Whether an activation email will be sent when the server is ready.
    """
    appId: int | None = None
    """
    The ID of the Vultr application to be installed on the server. See List Applications
    """
    appVariables: dict[str, str] | None = None
    """
    A map of user-supplied variable keys and values for Vultr Marketplace apps. See List Marketplace App Variables
    """
    cpuCount: int | None = None
    """
    The number of CPUs available on the server.
    """
    dateCreated: str | None = None
    """
    The date the server was added to your Vultr account.
    """
    disk: str | None = None
    """
    The description of the disk(s) on the server.
    """
    enableIpv6: bool | None = None
    """
    Whether the server has IPv6 networking activated.
    """
    gatewayV4: str | None = None
    """
    The server's IPv4 gateway.
    """
    hostname: str | None = None
    """
    The hostname to assign to the server.
    """
    id: str | None = None
    """
    ID of the server.
    """
    imageId: str | None = None
    """
    The ID of the Vultr marketplace application to be installed on the server. See List Applications Note marketplace applications are denoted by type: marketplace and you must use the image_id not the id.
    """
    label: str | None = None
    """
    A label for the server.
    """
    macAddress: int | None = None
    """
    The MAC address associated with the server.
    """
    mainIp: str | None = None
    """
    The server's main IP address.
    """
    mdiskMode: str | None = None
    """
    The raid configuration to use when provisioning the server.  Possible values: raid1, jbod, none. Defaults to none.
    """
    netmaskV4: str | None = None
    """
    The server's IPv4 netmask.
    """
    os: str | None = None
    """
    The string description of the operating system installed on the server.
    """
    osId: int | None = None
    """
    The ID of the operating system to be installed on the server. See List OS
    """
    persistentPxe: bool | None = None
    plan: str | None = None
    """
    The ID of the plan that you want the server to subscribe to. See List Plans
    """
    ram: str | None = None
    """
    The amount of memory available on the server in MB.
    """
    region: str | None = None
    """
    The ID of the region that the server is to be created in. See List Regions
    """
    reservedIpv4: str | None = None
    """
    The ID of the floating IP to use as the main IP of this server. See Reserved IPs
    """
    scriptId: str | None = None
    """
    The ID of the startup script you want added to the server.
    """
    snapshotId: str | None = None
    """
    The ID of the Vultr snapshot that the server will restore for the initial installation. See List Snapshots
    """
    sshKeyIds: list[str] | None = None
    """
    A list of SSH key IDs to apply to the server on install (only valid for Linux/FreeBSD).
    """
    status: str | None = None
    """
    The status of the server's subscription.
    """
    tags: list[str] | None = None
    """
    A list of tags to apply to the servier.
    """
    userData: str | None = None
    """
    Generic data store, which some provisioning tools and cloud operating systems use as a configuration file. It is generally consumed only once after an instance has been launched, but individual needs may vary.
    """
    userScheme: str | None = None
    """
    The scheme used for the default user. Possible values are root or limited (linux servers only).
    """
    v6MainIp: str | None = None
    """
    The main IPv6 network address.
    """
    v6Network: str | None = None
    """
    The IPv6 subnet.
    """
    v6NetworkSize: int | None = None
    """
    The IPv6 network size in bits.
    """
    vpc2Ids: list[str] | None = None
    """
    (Deprecated) A list of VPC 2.0 IDs to be attached to the server.
    """
    vpcId: str | None = None
    """
    The VPC ID to use when creating the server.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    lastHandledReconcileAt: str | None = None
    """
    LastHandledReconcileAt holds the value of the most recent
    reconcile-requested-at annotation token that the controller has
    processed. Users can compare this to the annotation to determine
    whether a reconcile request has been handled.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class BareMetalServer(BaseModel):
    apiVersion: Literal['compute.vultr.upbound.io/v1beta1'] | None = (
        'compute.vultr.upbound.io/v1beta1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['BareMetalServer'] | None = 'BareMetalServer'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    BareMetalServerSpec defines the desired state of BareMetalServer
    """
    status: Status | None = None
    """
    BareMetalServerStatus defines the observed state of BareMetalServer.
    """


class BareMetalServerList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[BareMetalServer]
    """
    List of baremetalservers. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """