# generated by datamodel-codegen:
#   filename:  workdir/network_vultr_upbound_io_v1beta1_natgatewayportforwardingrule.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from .....k8s.apimachinery.pkg.apis.meta import v1


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class NatGatewayIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class NatGatewayIdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class VpcIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class VpcIdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ForProvider(BaseModel):
    description: str | None = None
    """
    The description of the new port forwarding rule.
    """
    enabled: bool | None = None
    """
    Whether the new port forwarding rule is enabled or disabled.
    """
    externalPort: int | None = None
    """
    The external port of the new port forwarding rule.
    """
    internalIp: str | None = None
    """
    The internal IP address of the new port forwarding rule.
    """
    internalPort: int | None = None
    """
    The internal port of the new port forwarding rule.
    """
    name: str | None = None
    """
    The name of the new port forwarding rule.
    """
    natGatewayId: str | None = None
    """
    The NAT Gateway ID you want to attach this port forwarding rule to.
    """
    natGatewayIdRef: NatGatewayIdRef | None = None
    """
    Reference to a NATGateway in network to populate natGatewayId.
    """
    natGatewayIdSelector: NatGatewayIdSelector | None = None
    """
    Selector for a NATGateway in network to populate natGatewayId.
    """
    protocol: str | None = None
    """
    The protocol of the new port forwarding rule (tcp, udp, both).
    """
    vpcId: str | None = None
    """
    The VPC ID associated with the NAT Gateway you want to attach this to.
    """
    vpcIdRef: VpcIdRef | None = None
    """
    Reference to a VPC in network to populate vpcId.
    """
    vpcIdSelector: VpcIdSelector | None = None
    """
    Selector for a VPC in network to populate vpcId.
    """


class InitProvider(BaseModel):
    description: str | None = None
    """
    The description of the new port forwarding rule.
    """
    enabled: bool | None = None
    """
    Whether the new port forwarding rule is enabled or disabled.
    """
    externalPort: int | None = None
    """
    The external port of the new port forwarding rule.
    """
    internalIp: str | None = None
    """
    The internal IP address of the new port forwarding rule.
    """
    internalPort: int | None = None
    """
    The internal port of the new port forwarding rule.
    """
    name: str | None = None
    """
    The name of the new port forwarding rule.
    """
    natGatewayId: str | None = None
    """
    The NAT Gateway ID you want to attach this port forwarding rule to.
    """
    natGatewayIdRef: NatGatewayIdRef | None = None
    """
    Reference to a NATGateway in network to populate natGatewayId.
    """
    natGatewayIdSelector: NatGatewayIdSelector | None = None
    """
    Selector for a NATGateway in network to populate natGatewayId.
    """
    protocol: str | None = None
    """
    The protocol of the new port forwarding rule (tcp, udp, both).
    """
    vpcId: str | None = None
    """
    The VPC ID associated with the NAT Gateway you want to attach this to.
    """
    vpcIdRef: VpcIdRef | None = None
    """
    Reference to a VPC in network to populate vpcId.
    """
    vpcIdSelector: VpcIdSelector | None = None
    """
    Selector for a VPC in network to populate vpcId.
    """


class ProviderConfigRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class Spec(BaseModel):
    deletionPolicy: Literal['Orphan', 'Delete'] | None = 'Delete'
    """
    DeletionPolicy specifies what will happen to the underlying external
    when this managed resource is deleted - either "Delete" or "Orphan" the
    external resource.
    This field is planned to be deprecated in favor of the ManagementPolicies
    field in a future release. Currently, both could be set independently and
    non-default values would be honored if the feature flag is enabled.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    """
    forProvider: ForProvider
    initProvider: InitProvider | None = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    This field is planned to replace the DeletionPolicy field in a future
    release. Currently, both could be set independently and non-default
    values would be honored if the feature flag is enabled. If both are
    custom, the DeletionPolicy field will be ignored.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class AtProvider(BaseModel):
    dateCreated: str | None = None
    """
    The date the port forwarding rule was created.
    """
    dateUpdated: str | None = None
    """
    The date the port forwarding rule was last updated.
    """
    description: str | None = None
    """
    The description of the new port forwarding rule.
    """
    enabled: bool | None = None
    """
    Whether the new port forwarding rule is enabled or disabled.
    """
    externalPort: int | None = None
    """
    The external port of the new port forwarding rule.
    """
    id: str | None = None
    internalIp: str | None = None
    """
    The internal IP address of the new port forwarding rule.
    """
    internalPort: int | None = None
    """
    The internal port of the new port forwarding rule.
    """
    name: str | None = None
    """
    The name of the new port forwarding rule.
    """
    natGatewayId: str | None = None
    """
    The NAT Gateway ID you want to attach this port forwarding rule to.
    """
    protocol: str | None = None
    """
    The protocol of the new port forwarding rule (tcp, udp, both).
    """
    vpcId: str | None = None
    """
    The VPC ID associated with the NAT Gateway you want to attach this to.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    lastHandledReconcileAt: str | None = None
    """
    LastHandledReconcileAt holds the value of the most recent
    reconcile-requested-at annotation token that the controller has
    processed. Users can compare this to the annotation to determine
    whether a reconcile request has been handled.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class NATGatewayPortForwardingRule(BaseModel):
    apiVersion: Literal['network.vultr.upbound.io/v1beta1'] | None = (
        'network.vultr.upbound.io/v1beta1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['NATGatewayPortForwardingRule'] | None = (
        'NATGatewayPortForwardingRule'
    )
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    NATGatewayPortForwardingRuleSpec defines the desired state of NATGatewayPortForwardingRule
    """
    status: Status | None = None
    """
    NATGatewayPortForwardingRuleStatus defines the observed state of NATGatewayPortForwardingRule.
    """


class NATGatewayPortForwardingRuleList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[NATGatewayPortForwardingRule]
    """
    List of natgatewayportforwardingrules. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """